#include "DesignerExport.h"
#include "DesignerCodeGen.h"

namespace Upp {

static String ExportFilePlaceholder(const String& value, const char *placeholder)
{
	String text = TrimBoth(value);
	return text.IsEmpty() ? String("[") + placeholder + "]" : text;
}

static bool EnsureDirectoryPath(const String& path)
{
	String p = NormalizePath(path);
	if(p.IsEmpty())
		return false;
	if(DirectoryExists(p))
		return true;
	String parent = GetFileFolder(p);
	if(!parent.IsEmpty() && parent != p && !DirectoryExists(parent) && !EnsureDirectoryPath(parent))
		return false;
	return DirectoryCreate(p) || DirectoryExists(p);
}

static bool DirectoryHasFiles(const String& path)
{
	FindFile ff(AppendFileName(path, "*"));
	return ff;
}

static bool WriteFileAtomic(const String& path, const String& data)
{
	String tmp = path + ".tmp";
	if(!SaveFile(tmp, data))
		return false;
	if(FileExists(path) && !FileDelete(path)) {
		FileDelete(tmp);
		return false;
	}
	if(!FileMove(tmp, path)) {
		FileDelete(tmp);
		return false;
	}
	return true;
}

static bool WriteExportFile(const String& path, const String& data)
{
	return WriteFileAtomic(path, data);
}

static bool RemovePathIfExists(const String& path)
{
	if(DirectoryExists(path))
		return DeleteFolderDeep(path);
	if(FileExists(path))
		return FileDelete(path);
	return true;
}

static bool MovePath(const String& from, const String& to)
{
	if(!RemovePathIfExists(to))
		return false;
	return FileMove(from, to);
}

static String BuildUppFile(const DesignerProjectExportOptions& options, const String& project_name)
{
	String out;
	out << "uses\n"
	    << "\tCore,\n"
	    << "\tDraw,\n"
	    << "\tCtrlCore,\n"
	    << "\tCtrlLib,\n"
	    << "\tUi;\n\n"
	    << "file\n"
	    << "\tmain.cpp";
	if(options.include_design_json)
		out << ",\n\tdesign.json";
	if(options.include_readme)
		out << ",\n\tREADME.md";
	out << ";\n\n"
	    << "mainconfig\n"
	    << "\t\"\" = \"GUI\";\n";
	return out;
}

static String BuildReadme(const DesignerProjectExportOptions& options,
                          const DesignerProjectExportResult& result)
{
	String umk_path = ExportFilePlaceholder(options.umk_path, "PATH_TO_UPP_OR_UMK");
	String package_path = ExportFilePlaceholder(GetFileFolder(result.package_dir), "PATH_TO_EXPORTED_PACKAGE");
	String build_method = ExportFilePlaceholder(options.build_method, "BUILD_METHOD");
	String output_exe = ExportFilePlaceholder(options.output_exe_path, "PATH_TO_OUTPUT_EXE");

	String out;
	out << "# " << result.project_name << "\n\n"
	    << "Generated by U++ Ui Designer.\n\n"
	    << "## Open in TheIDE\n\n"
	    << "Add `" << package_path << "` as a package nest if needed, then open the package `" << result.project_name << "`.\n\n"
	    << "## Command-line build\n\n"
	    << "```text\n"
	    << umk_path << " " << package_path << " " << result.project_name << " " << build_method << " -br +GUI " << output_exe << "\n"
	    << "```\n\n"
	    << "- `main.cpp` is generated output.\n"
	    << "- `design.json` is the source design model for regeneration.\n";
	return out;
}

String SanitizeDesignerPackageName(String text, const String& fallback)
{
	text = TrimBoth(text);
	String out;
	bool last_us = false;
	for(int i = 0; i < text.GetCount(); i++) {
		int c = text[i];
		if(IsAlNum(c) || c == '_') {
			if(out.IsEmpty() && IsDigit(c))
				out << '_';
			out.Cat(c);
			last_us = false;
		}
		else if(!out.IsEmpty() && !last_us) {
			out << '_';
			last_us = true;
		}
	}
	while(out.GetCount() && out[out.GetCount() - 1] == '_')
		out.Trim(out.GetCount() - 1);
	return out.IsEmpty() ? fallback : out;
}

String SanitizeDesignerClassName(String text, const String& fallback)
{
	String out = SanitizeDesignerPackageName(text, fallback);
	if(out.IsEmpty())
		return fallback;
	if(IsDigit(out[0]))
		out.Insert(0, '_');
	return out;
}

bool ExportDesignerProject(const DesignerModel& model, const DesignerRegistry& registry,
                           const DesignerProjectExportOptions& options,
                           const String& design_json,
                           DesignerProjectExportResult& result)
{
	result = DesignerProjectExportResult();
	result.project_name = SanitizeDesignerPackageName(options.project_name);
	result.class_name = SanitizeDesignerClassName(options.class_name);

	String out_dir = TrimBoth(options.output_directory);
	if(result.project_name.IsEmpty()) {
		result.error = "Project name is empty.";
		return false;
	}
	if(result.class_name.IsEmpty()) {
		result.error = "Generated class name is empty.";
		return false;
	}
	if(out_dir.IsEmpty()) {
		result.error = "Output directory is empty.";
		return false;
	}
	result.package_dir = AppendFileName(out_dir, result.project_name);
	String stage_dir = result.package_dir + ".staging";
	if(DirectoryExists(result.package_dir) && DirectoryHasFiles(result.package_dir) && !options.overwrite_existing) {
		result.error = "Export directory already exists and is not empty.";
		return false;
	}
	if(DirectoryExists(stage_dir) && !DeleteFolderDeep(stage_dir)) {
		result.error = "Unable to clear staging directory.";
		return false;
	}
	if(!EnsureDirectoryPath(stage_dir)) {
		result.error = "Unable to create export directory.";
		return false;
	}

	result.upp_path = AppendFileName(result.package_dir, result.project_name + ".upp");
	result.main_cpp_path = AppendFileName(result.package_dir, "main.cpp");
	result.design_json_path = AppendFileName(result.package_dir, "design.json");
	result.readme_path = AppendFileName(result.package_dir, "README.md");
	String stage_upp_path = AppendFileName(stage_dir, result.project_name + ".upp");
	String stage_main_cpp_path = AppendFileName(stage_dir, "main.cpp");
	String stage_design_json_path = AppendFileName(stage_dir, "design.json");
	String stage_readme_path = AppendFileName(stage_dir, "README.md");

	DesignerCodeGenOptions gen;
	gen.class_name = result.class_name;
	gen.emit_designer_appearance = options.include_designer_appearance;
	gen.emit_export_header = true;
	gen.source_design_filename = options.source_design_filename;
	gen.package_name = result.project_name;
	gen.umk_path = options.umk_path;
	gen.exported_package_path = result.package_dir;
	gen.build_method = options.build_method;
	gen.output_exe_path = options.output_exe_path;

	String main_cpp = GenerateDesignerCode(model, registry, gen);
	String upp = BuildUppFile(options, result.project_name);
	String readme = BuildReadme(options, result);

	if(!WriteExportFile(stage_upp_path, upp) || !WriteExportFile(stage_main_cpp_path, main_cpp)) {
		result.error = "Unable to write exported project files.";
		DeleteFolderDeep(stage_dir);
		return false;
	}
	if(options.include_design_json && !WriteExportFile(stage_design_json_path, design_json)) {
		result.error = "Unable to write design.json.";
		DeleteFolderDeep(stage_dir);
		return false;
	}
	if(options.include_readme && !WriteExportFile(stage_readme_path, readme)) {
		result.error = "Unable to write README.md.";
		DeleteFolderDeep(stage_dir);
		return false;
	}

	String backup_dir = result.package_dir + ".backup";
	bool final_exists = DirectoryExists(result.package_dir) || FileExists(result.package_dir);
	bool final_has_files = DirectoryExists(result.package_dir) && DirectoryHasFiles(result.package_dir);
	bool use_backup = final_exists && options.overwrite_existing && final_has_files;
	if(DirectoryExists(backup_dir) && !DeleteFolderDeep(backup_dir)) {
		result.error = "Unable to clear backup directory.";
		DeleteFolderDeep(stage_dir);
		return false;
	}
	if(use_backup) {
		if(!MovePath(result.package_dir, backup_dir)) {
			result.error = "Unable to save existing export directory.";
			DeleteFolderDeep(stage_dir);
			return false;
		}
	}
	else if(final_exists && !final_has_files) {
		if(!RemovePathIfExists(result.package_dir)) {
			result.error = "Unable to clear existing empty export directory.";
			DeleteFolderDeep(stage_dir);
			return false;
		}
	}

	auto RestoreBackup = [&]() -> bool {
		RemovePathIfExists(result.package_dir);
		if(options.simulate_restore_failure)
			return false;
		if(DirectoryExists(backup_dir) || FileExists(backup_dir))
			return MovePath(backup_dir, result.package_dir);
		return true;
	};

	if(options.simulate_commit_failure) {
		result.error = "Simulated export commit failure.";
		bool restored = RestoreBackup();
		DeleteFolderDeep(stage_dir);
		if(restored)
			RemovePathIfExists(backup_dir);
		else
			result.error << " Existing export backup could not be restored; backup left at " << backup_dir;
		return false;
	}

	if(!MovePath(stage_dir, result.package_dir)) {
		result.error = "Unable to finalize exported project.";
		bool restored = !use_backup || RestoreBackup();
		DeleteFolderDeep(stage_dir);
		if(restored)
			RemovePathIfExists(backup_dir);
		else
			result.error << " Existing export backup could not be restored; backup left at " << backup_dir;
		return false;
	}

	RemovePathIfExists(backup_dir);
	return true;
}

}
