// Generated by U++ Ui Designer.
// Designer version: v1.0.0-rc1
// Appearance mode: ThemeFirst
// Source design: design_themestudio.json
// Package: design_themestudio
// UMK path: E:\upp-18468\umk.exe
// Exported package: E:\apps\github\upp_Ui\Utilities\DesignerThemeStudioExport
// Build method: CLANGx64
// Output executable: [PATH_TO_OUTPUT_EXE]
// Regenerate from design.json when the Designer model changes.
// This file is theme-first generated output.
// Explicit Designer appearance overrides are marked in code.

#include <CtrlLib/CtrlLib.h>
#include <Ui/Ui.h>

using namespace Upp;

// -----------------------------------------------------------------------------
// Theme candidates
// -----------------------------------------------------------------------------
// Designer appearance export omitted in theme-first mode.
// Instance-specific text, layout, data, and event wiring remain outside this section.

class design_themestudioWindow : public TopWindow {
public:
	typedef design_themestudioWindow CLASSNAME;

	design_themestudioWindow()
	{
		InitWindow();
		InitThemeContext();
		BuildControls();
		ApplyAppearanceOverrides();
		BuildLayout();
		PostBuild();
	}

private:
	void InitWindow()
	{
		Title("Generated Designer Layout");
		Sizeable().Zoomable();
		SetRect(0, 0, DPI(1374), DPI(858));
	}

	void InitThemeContext()
	{
		// Move this method to GeneratedDesignerTheme.cpp if splitting the generated app.
		// Theme context / preset setup.
	}

	void BuildControls()
	{
		// Control text, icons, values, ranges, roles, and basic behaviour.
		main_window_layout.SetDirection(UiDirection::V).SetGap(DPI(0), DPI(0)).SetInset(DPI(0)).SetWrap(UiBoxWrap::None);
		top_layout.SetDirection(UiDirection::H).SetGap(DPI(8), DPI(8)).SetInset(DPI(6)).SetWrap(UiBoxWrap::Flow).SetWrapAutoResize(true);
		center_layout.SetDirection(UiDirection::H).SetGap(DPI(0), DPI(0)).SetInset(DPI(0)).SetWrap(UiBoxWrap::None);
		lower_layout.SetDirection(UiDirection::V).SetGap(DPI(8), DPI(8)).SetInset(DPI(0)).SetWrap(UiBoxWrap::None);
		header_title_card.SetCustomStyle(UiTheme::ResolveTitleCard(UiRole::Accent));
		header_title_card.SetTitle("Theme Studio").SetSubTitle("").SetContentInset(DPI(4)).SetMediaGap(DPI(9)).SetMediaReserve(DPI(0)).SetMediaMin(DPI(15)).SetMediaAutoFit(false).SetMediaSide(UiAlign::LEFT).SetMediaAlign(UiAlign::CENTER, UiAlign::CENTER).ShowTitleLine(false).ShowCardLine(false);
		header_title_card.SetMedia(ICON_BRAND_NEWLOGO_V5_48(), Size(DPI(18), DPI(18)));
		save_split_btn.SetCustomStyle(UiTheme::ResolveButton(UiRole::Accent));
		save_split_btn.SetMinSize(Size(DPI(74), DPI(24)));
		save_split_btn.SetText("Save").SetContentInset(DPI(6)).SetContentGap(DPI(6));
		save_split_btn.SetSplitWidth(DPI(31));
		save_split_btn.SetSplitContentGap(DPI(4));
		save_split_btn.SetSplitIconSize(DPI(10));
		save_split_btn.SetPopupMinWidth(DPI(220));
		save_split_btn.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		save_split_btn.SetIconSide(UiAlign::LEFT);
		save_split_btn.Add("Recent A", "a").Add("Recent B", "b").Add("Recent C", "c");
		theme_selection_drop_down.SetCustomStyle(UiTheme::ResolveDropdown(UiRole::Subtle));
		theme_selection_drop_down.SetMinSize(Size(DPI(124), DPI(0)));
		theme_selection_drop_down.UseInternalModel().Clear().Add("Theme", "Theme");
		theme_selection_drop_down.Select(0);
		theme_selection_drop_down.SetIndicatorSide(UiAlign::RIGHT);
		theme_selection_drop_down.SetIndicatorSize(DPI(14));
		help_tool.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Accent));
		help_tool.SetMinSize(Size(DPI(60), DPI(0)));
		help_tool.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		help_tool.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		help_tool.SetIconSide(UiAlign::LEFT);
		help_tool.SetIcon(ICON_DESIGN_HELP_48()).SetIconSize(DPI(16), DPI(16));
		lower__label.SetText("Label");
		lower__label.SetAlign(UiAlign::LEFT, UiAlign::CENTER);
		lower__label.SetIconSide(UiAlign::LEFT);
		lower__label.SetContentGap(DPI(6));
		lower__label.SetIconScaleToContent(false);
		version_label.SetCustomStyle(UiTheme::ResolveLabel(UiRole::Accent));
		version_label.SetMinSize(Size(DPI(76), DPI(28)));
		version_label.SetText("v2.3.1");
		version_label.SetAlign(UiAlign::LEFT, UiAlign::CENTER);
		version_label.SetIconSide(UiAlign::LEFT);
		version_label.SetContentGap(DPI(5));
		version_label.SetIconScaleToContent(false);
		version_label.SetIcon(ICON_DESIGN_ADJUST_48(), UiIconRenderMode::MonoTint).SetIconSize(DPI(10), DPI(10));
		dark_theme_tool.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Accent));
		dark_theme_tool.SetMinSize(Size(DPI(60), DPI(0)));
		dark_theme_tool.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		dark_theme_tool.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		dark_theme_tool.SetIconSide(UiAlign::LEFT);
		dark_theme_tool.SetIcon(ICON_ACTION_DARK_MODE_48()).SetIconSize(DPI(16), DPI(16));
		right_layout.SetDirection(UiDirection::V).SetGap(DPI(0), DPI(0)).SetInset(DPI(0)).SetWrap(UiBoxWrap::Flow).SetWrapAutoResize(true);
		controls_tool.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		controls_tool.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		controls_tool.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		controls_tool.SetIconSide(UiAlign::LEFT);
		controls_tool.SetIcon(ICON_DESIGN_WIDGETS_48()).SetIconSize(DPI(16), DPI(16));
		controls_tool.Tip("Controls");
		composites_tool.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		composites_tool.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		composites_tool.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		composites_tool.SetIconSide(UiAlign::LEFT);
		composites_tool.SetIcon(ICON_DESIGN_DYNAMIC_FORM_48()).SetIconSize(DPI(16), DPI(16));
		composites_tool.Tip("Composites");
		right_tools_panel.SetCustomStyle(UiTheme::ResolvePanel(UiRole::Subtle));
		right_tools_panel.SetSizeMin(DPI(0), DPI(0));
		right_tools_panel.SetInset(DPI(0));
		right_tools_layout.SetDirection(UiDirection::H).SetGap(DPI(8), DPI(8)).SetInset(DPI(19)).SetWrap(UiBoxWrap::None);
		code_tool.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		code_tool.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		code_tool.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		code_tool.SetIconSide(UiAlign::LEFT);
		code_tool.SetIcon(ICON_DESIGN_CODE_BLOCKS_48()).SetIconSize(DPI(16), DPI(16));
		code_tool.Tip("Code");
		overrides_tool.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		overrides_tool.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		overrides_tool.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		overrides_tool.SetIconSide(UiAlign::LEFT);
		overrides_tool.SetIcon(ICON_DESIGN_FORMAT_PAINT_48()).SetIconSize(DPI(16), DPI(16));
		overrides_tool.Tip("Theme Overrides ");
		inspector_tool.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		inspector_tool.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		inspector_tool.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		inspector_tool.SetIconSide(UiAlign::LEFT);
		inspector_tool.SetIcon(ICON_DESIGN_TUNE_48()).SetIconSize(DPI(16), DPI(16));
		inspector_tool.Tip("Inspector ");
		hierarchy_tool.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		hierarchy_tool.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		hierarchy_tool.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		hierarchy_tool.SetIconSide(UiAlign::LEFT);
		hierarchy_tool.SetIcon(ICON_DESIGN_ACCOUNT_TREE_48()).SetIconSize(DPI(16), DPI(16));
		hierarchy_tool.Tip("Hierarchy tree");
		right_open_close_btn.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		right_open_close_btn.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		right_open_close_btn.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		right_open_close_btn.SetIconSide(UiAlign::LEFT);
		right_open_close_btn.SetIcon(ICON_DESIGN_RIGHT_PANEL_CLOSE_48()).SetIconSize(DPI(16), DPI(16));
		right_info_panel.SetMinSize(Size(DPI(0), DPI(1)));
		right_info_panel.SetInset(DPI(0));
		right_info_panel.SetScrollMode(UIPANELSCROLL_AUTO);
		center_panel.SetCustomStyle(UiTheme::ResolvePanel(UiRole::Subtle));
		center_panel.SetSizeMin(DPI(0), DPI(0));
		center_panel.SetInset(DPI(0));
		center_layout_02.SetDirection(UiDirection::V).SetGap(DPI(0), DPI(0)).SetInset(DPI(0)).SetWrap(UiBoxWrap::None).SetDebugColor(Color(220, 38, 38)).SetDebug(true);
		center_tools_panel.SetCustomStyle(UiTheme::ResolvePanel(UiRole::Subtle));
		center_tools_panel.SetSizeMin(DPI(0), DPI(0));
		center_tools_panel.SetInset(DPI(0));
		center_tools_panel.Tip("Set size or aspect ratio");
		center_preview_panel.SetCustomStyle(UiTheme::ResolveScrollPanel(UiRole::Subtle));
		center_preview_panel.SetInset(DPI(0));
		center_preview_panel.SetScrollMode(UIPANELSCROLL_AUTO);
		center_tools_layout.SetDirection(UiDirection::H).SetGap(DPI(8), DPI(8)).SetInset(DPI(19)).SetWrap(UiBoxWrap::None);
		right_expand_toggle_btn.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		right_expand_toggle_btn.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		right_expand_toggle_btn.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		right_expand_toggle_btn.SetIconSide(UiAlign::LEFT);
		right_expand_toggle_btn.SetIcon(ICON_DESIGN_UNFOLD_MORE_48()).SetIconSize(DPI(16), DPI(16));
		right_expand_toggle_btn.Tip("Expand toggle");
		export_split_btn.SetCustomStyle(UiTheme::ResolveButton(UiRole::Accent));
		export_split_btn.SetMinSize(Size(DPI(74), DPI(24)));
		export_split_btn.SetText("Export").SetContentInset(DPI(6)).SetContentGap(DPI(6));
		export_split_btn.SetSplitWidth(DPI(31));
		export_split_btn.SetSplitContentGap(DPI(4));
		export_split_btn.SetSplitIconSize(DPI(10));
		export_split_btn.SetPopupMinWidth(DPI(220));
		export_split_btn.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		export_split_btn.SetIconSide(UiAlign::LEFT);
		export_split_btn.Add("Header/Cpp", "a").Add("Cpp (Main)", "b").Add("Theam (only)", "c");
		exit_tool.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Alert));
		exit_tool.SetMinSize(Size(DPI(60), DPI(0)));
		exit_tool.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		exit_tool.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		exit_tool.SetIconSide(UiAlign::LEFT);
		exit_tool.SetIcon(ICON_DESIGN_CANCEL_48()).SetIconSize(DPI(16), DPI(16));
		exit_tool.Tip("Close theme studio");
		button.SetMinSize(Size(DPI(91), DPI(0)));
		button.SetText("Normal").SetContentInset(DPI(6)).SetContentGap(DPI(4));
		button.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		button.SetIconSide(UiAlign::LEFT);
		button.Tip("Normal role");
		button_02.SetMinSize(Size(DPI(91), DPI(0)));
		button_02.SetText("Subtle").SetContentInset(DPI(6)).SetContentGap(DPI(4));
		button_02.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		button_02.SetIconSide(UiAlign::LEFT);
		button_02.Tip("Subtle Role");
		button_03.SetMinSize(Size(DPI(91), DPI(0)));
		button_03.SetText("Accent").SetContentInset(DPI(6)).SetContentGap(DPI(4));
		button_03.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		button_03.SetIconSide(UiAlign::LEFT);
		button_03.Tip("Accent Role");
		button_04.SetMinSize(Size(DPI(91), DPI(0)));
		button_04.SetText("Alert").SetContentInset(DPI(6)).SetContentGap(DPI(4));
		button_04.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		button_04.SetIconSide(UiAlign::LEFT);
		button_04.Tip("Alert Role");
		boxlayout.SetDirection(UiDirection::V).SetGap(DPI(8), DPI(8)).SetInset(DPI(0)).SetWrap(UiBoxWrap::None);
		lower_grid.SetGridSize(3, 2).SetMinCellSize(Size(DPI(25), DPI(25))).SetGap(DPI(8)).SetInset(DPI(0)).SetDebugColor(Color(220, 38, 38)).SetDebug(true);
		panel.SetSizeMin(DPI(0), DPI(0));
		panel.SetInset(DPI(0));
		gridlayout.SetGridSize(2, 1).SetMinCellSize(Size(DPI(25), DPI(25))).SetGap(DPI(10)).SetInset(DPI(1));
		titlecard.SetTitle("Main Title Card Theme").SetSubTitle("Subtitle theme represented here").SetContentInset(DPI(7)).SetMediaGap(DPI(10)).SetMediaReserve(DPI(24)).SetMediaMin(DPI(16)).SetMediaAutoFit(false).SetMediaSide(UiAlign::LEFT).SetMediaAlign(UiAlign::CENTER, UiAlign::CENTER).ShowTitleLine(true).ShowCardLine(false);
		titlecard.SetMedia(ICON_BRAND_NEWLOGO_V5_48(), Size(DPI(29), DPI(29)));
		panel_02.SetSizeMin(DPI(0), DPI(0));
		panel_02.SetInset(DPI(0));
		gridlayout_02.SetGridSize(2, 2).SetMinCellSize(Size(DPI(25), DPI(25))).SetGap(DPI(0)).SetInset(DPI(8));
		label.SetText(" Second toggle theme");
		label.SetAlign(UiAlign::LEFT, UiAlign::CENTER);
		label.SetIconSide(UiAlign::LEFT);
		label.SetContentGap(DPI(6));
		label.SetIconScaleToContent(false);
		label.SetIcon(ICON_DESIGN_CIRCLE_CIRCLE_48(), UiIconRenderMode::MonoTint).SetIconSize(DPI(12), DPI(12));
		label_02.SetText(" First toggle theme ");
		label_02.SetAlign(UiAlign::LEFT, UiAlign::CENTER);
		label_02.SetIconSide(UiAlign::LEFT);
		label_02.SetContentGap(DPI(6));
		label_02.SetIconScaleToContent(false);
		label_02.SetIcon(ICON_DESIGN_CIRCLE_CIRCLE_48(), UiIconRenderMode::MonoTint).SetIconSize(DPI(12), DPI(12));
		toggle.SetOn(true);
		toggle_02.SetOn(true);
		grouppanel_02.SetTitle("BUTTON THEMES").SetSubTitle(" Various buttons for theming. ").SetSideTitle("").SetHeaderMode(UiGroupPanel::Inside).SetHeaderPlacement(UiAlign::TOP).SetLine(false).SetHeaderBand(false).SetLineThickness(DPI(1)).SetInset(Rect(DPI(0), DPI(0), DPI(0), DPI(0))).SetHeaderInset(Rect(DPI(8), DPI(8), DPI(8), DPI(8)))		gridlayout_03.SetGridSize(1, 3).SetMinCellSize(Size(DPI(25), DPI(25))).SetGap(DPI(8)).SetInset(DPI(0)).SetDebugColor(Color(220, 38, 38)).SetDebug(true);
		gridlayout_04.SetGridSize(1, 3).SetMinCellSize(Size(DPI(25), DPI(25))).SetGap(DPI(8)).SetInset(DPI(0));
		gridlayout_05.SetGridSize(2, 1).SetMinCellSize(Size(DPI(25), DPI(25))).SetGap(DPI(8)).SetInset(DPI(0));
		grouppanel_03.SetTitle("INTERGER").SetSubTitle("").SetSideTitle("").SetHeaderMode(UiGroupPanel::Inside).SetHeaderPlacement(UiAlign::TOP).SetLine(false).SetHeaderBand(false).SetLineThickness(DPI(1)).SetInset(Rect(DPI(8), DPI(8), DPI(8), DPI(8))).SetHeaderInset(Rect(DPI(6), DPI(6), DPI(6), DPI(6)))		grouppanel_04.SetTitle("Group").SetSubTitle("").SetSideTitle("").SetHeaderMode(UiGroupPanel::Inside).SetHeaderPlacement(UiAlign::TOP).SetLine(false).SetHeaderBand(false).SetLineThickness(DPI(1)).SetInset(Rect(DPI(8), DPI(8), DPI(8), DPI(8))).SetHeaderInset(Rect(DPI(6), DPI(6), DPI(6), DPI(6)))		grouppanel_06.SetTitle("DOCUMENT").SetSubTitle("").SetSideTitle("").SetHeaderMode(UiGroupPanel::Inside).SetHeaderPlacement(UiAlign::TOP).SetLine(false).SetHeaderBand(false).SetLineThickness(DPI(1)).SetInset(Rect(DPI(8), DPI(8), DPI(8), DPI(8))).SetHeaderInset(Rect(DPI(6), DPI(6), DPI(6), DPI(6)))		grouppanel_07.SetTitle(" Split Button ").SetSubTitle("").SetSideTitle("").SetHeaderMode(UiGroupPanel::Inside).SetHeaderPlacement(UiAlign::TOP).SetLine(false).SetHeaderBand(false).SetLineThickness(DPI(1)).SetInset(Rect(DPI(8), DPI(8), DPI(8), DPI(8))).SetHeaderInset(Rect(DPI(6), DPI(6), DPI(6), DPI(6)))		grouppanel_08.SetTitle(" Bread-Crumbs ").SetSubTitle("").SetSideTitle("").SetHeaderMode(UiGroupPanel::Inside).SetHeaderPlacement(UiAlign::TOP).SetLine(false).SetHeaderBand(false).SetLineThickness(DPI(1)).SetInset(Rect(DPI(8), DPI(8), DPI(8), DPI(8))).SetHeaderInset(Rect(DPI(6), DPI(6), DPI(6), DPI(6)))		gridlayout_06.SetGridSize(2, 1).SetMinCellSize(Size(DPI(25), DPI(25))).SetGap(DPI(8)).SetInset(DPI(0)).SetDebugColor(Color(220, 38, 38)).SetDebug(true);
		grouppanel_09.SetTitle("Standard Button").SetSubTitle("").SetSideTitle("").SetHeaderMode(UiGroupPanel::Inside).SetHeaderPlacement(UiAlign::TOP).SetLine(false).SetHeaderBand(false).SetLineThickness(DPI(1)).SetInset(Rect(DPI(8), DPI(8), DPI(8), DPI(8))).SetHeaderInset(Rect(DPI(6), DPI(6), DPI(6), DPI(6)))		grouppanel_10.SetTitle("Tool Button").SetSubTitle("").SetSideTitle("").SetHeaderMode(UiGroupPanel::Inside).SetHeaderPlacement(UiAlign::TOP).SetLine(false).SetHeaderBand(false).SetLineThickness(DPI(1)).SetInset(Rect(DPI(8), DPI(8), DPI(8), DPI(8))).SetHeaderInset(Rect(DPI(6), DPI(6), DPI(6), DPI(6)))		button_05.SetMinSize(Size(DPI(124), DPI(0)));
		button_05.SetText("Button").SetContentInset(DPI(6)).SetContentGap(DPI(4));
		button_05.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		button_05.SetIconSide(UiAlign::LEFT);
		toolbutton.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		toolbutton.SetAlign(UiAlign::LEFT, UiAlign::CENTER);
		toolbutton.SetIconSide(UiAlign::LEFT);
		toolbutton.SetIcon(ICON_DESIGN_SETTINGS_48()).SetIconSize(DPI(20), DPI(20));
		splitbutton.SetText("Save").SetContentInset(DPI(6)).SetContentGap(DPI(4));
		splitbutton.SetSplitWidth(DPI(30));
		splitbutton.SetSplitContentGap(DPI(4));
		splitbutton.SetSplitIconSize(DPI(16));
		splitbutton.SetPopupMinWidth(DPI(220));
		splitbutton.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		splitbutton.SetIconSide(UiAlign::LEFT);
		splitbutton.Add("Recent A", "a").Add("Recent B", "b").Add("Recent C", "c");
		breadcrumbs.AddCrumb("Home", "0");
		breadcrumbs.AddCrumb("Library", "1");
		breadcrumbs.AddCrumb("Current", "2");
		breadcrumbs.SetCurrentIndex(2);
		breadcrumbs.SetTrimOnSelect(false).SetDivider("/");
		breadcrumbs.SetPathIcon(ICON_DESIGN_HOME_48(), UiAlign::LEFT, Size(DPI(16), DPI(16)));
		intedit.MinMax(0, 100).Step(1).ShowSpin(true);
		intedit.SetValue(42);
		floatedit.MinMax(0, 100).Step(0.1).Precision(2).ShowSpin(true);
		floatedit.SetValue(3.14);
		gridlayout_07.SetGridSize(2, 1).SetMinCellSize(Size(DPI(25), DPI(25))).SetGap(DPI(8)).SetInset(DPI(0));
		grouppanel_03_02.SetTitle("MASK").SetSubTitle("").SetSideTitle("").SetHeaderMode(UiGroupPanel::Inside).SetHeaderPlacement(UiAlign::TOP).SetLine(false).SetHeaderBand(false).SetLineThickness(DPI(1)).SetInset(Rect(DPI(8), DPI(8), DPI(8), DPI(8))).SetHeaderInset(Rect(DPI(6), DPI(6), DPI(6), DPI(6)))		grouppanel_03_03.SetTitle("PASSWORD").SetSubTitle("").SetSideTitle("").SetHeaderMode(UiGroupPanel::Inside).SetHeaderPlacement(UiAlign::TOP).SetLine(false).SetHeaderBand(false).SetLineThickness(DPI(1)).SetInset(Rect(DPI(8), DPI(8), DPI(8), DPI(8))).SetHeaderInset(Rect(DPI(6), DPI(6), DPI(6), DPI(6)))		maskedit.SetMask("##/##/####", '_');
		maskedit.SetPlaceholder("Masked value");
		maskedit.ShowError(false);
		passwordedit.SetTextUtf8("Password");
		passwordedit.SetPlaceholder("Password");
		passwordedit.SetPasswordChar(8226);
		passwordedit.SetPlainTextVisible(false);
		passwordedit.EnableVisibilityIcon(true);
		doc.SetText("UiDoc sample");
		grouppanel_11.SetTitle("ACCORDION").SetSubTitle("").SetSideTitle("").SetHeaderMode(UiGroupPanel::Inside).SetHeaderPlacement(UiAlign::TOP).SetLine(false).SetHeaderBand(false).SetLineThickness(DPI(1)).SetInset(Rect(DPI(0), DPI(0), DPI(0), DPI(0))).SetHeaderInset(Rect(DPI(6), DPI(6), DPI(6), DPI(6)))		grouppanel_12.SetTitle("TAB").SetSubTitle("Tab containing editable fields").SetSideTitle("").SetHeaderMode(UiGroupPanel::Inside).SetHeaderPlacement(UiAlign::TOP).SetLine(false).SetHeaderBand(false).SetLineThickness(DPI(1)).SetInset(Rect(DPI(0), DPI(0), DPI(0), DPI(0))).SetHeaderInset(Rect(DPI(6), DPI(6), DPI(6), DPI(6)))		{
			UiTab::Style s = UiTheme::ResolveTab(UiRole::Standard, UITAB_UNDERLINE);
			s.metrics.face_enabled = false;
			s.metrics.frame_enabled = false;
			s.metrics.radius = DPI(0);
			s.content_gap = DPI(5);
			s.affordance_gap = DPI(4);
			tab_02.SetCustomStyle(s);
		}
		tab_02.SetVisual(UITAB_UNDERLINE).SetPlacement(UiAlign::TOP).SetExpandTabs(false).EnableCloseButtons(false).EnableDragHandles(false);
		tab_02.SetTabFont(SansSerifZ(11)).SetTabIconSize(DPI(16)).SetTabIconSide(UiAlign::LEFT);
		tab_02.SetContentGap(DPI(5)).SetAffordanceGap(DPI(4));
		// DESIGNER CODEGEN CONTRACT ERROR: PageSlot missing setup hook
		// DESIGNER CODEGEN CONTRACT ERROR: PageSlot missing setup hook
		// DESIGNER CODEGEN CONTRACT ERROR: PageSlot missing setup hook
		tree.GetInternalModel().AddChild(tree.GetInternalModel().Root(), UiModelItem("Workspace", "workspace"));
		tree.ShowConnectorLines(true);
		table.UseInternalModel();
		table.GetInternalModel().SetSize(4, 2);
		gridlayout_09.SetGridSize(1, 2).SetMinCellSize(Size(DPI(25), DPI(25))).SetGap(DPI(8)).SetInset(DPI(8)).SetDebugColor(Color(220, 38, 38)).SetDebug(true);
		accordion.SetSingleOpen(false).SetEnforceOne(false).ShowChevron(true).SetChevronSide(UiAlign::RIGHT).SetAnimation(true, 120, 0).ShowDragHandle(false).EnableDragReorder(false);
		// DESIGNER CODEGEN CONTRACT ERROR: AccordionSectionSlot missing setup hook
		// DESIGNER CODEGEN CONTRACT ERROR: AccordionSectionSlot missing setup hook
		// DESIGNER CODEGEN CONTRACT ERROR: AccordionSectionSlot missing setup hook
		grouppanel.SetTitle("SLIDERS").SetSubTitle("").SetSideTitle("").SetHeaderMode(UiGroupPanel::Inside).SetHeaderPlacement(UiAlign::TOP).SetLine(false).SetHeaderBand(false).SetLineThickness(DPI(1)).SetInset(Rect(DPI(8), DPI(8), DPI(8), DPI(8))).SetHeaderInset(Rect(DPI(6), DPI(6), DPI(6), DPI(6)))		gridlayout_08.SetGridSize(1, 2).SetMinCellSize(Size(DPI(25), DPI(25))).SetGap(DPI(8)).SetInset(DPI(8)).SetDebugColor(Color(220, 38, 38)).SetDebug(true);
		progressbar.SetCustomStyle(UiTheme::ResolveProgressBar(UiRole::Accent));
		progressbar.Percent(true).SetOrientation(UiProgressBar::Orientation::Auto);
		progressbar.Set(60, 100);
		slider.SetRange(0, 100).SetValue(50);
	}

	void ApplyAppearanceOverrides()
	{
		// Designer appearance export omitted; theme-first output only.
	}

	void BuildLayout()
	{
		// Parent-child layout tree only.
		Add(main_window_layout);
		main_window_layout.Add(top_layout).Fit().MinCross(DPI(0)).AlignSelf(UiBoxLayout::Align::Stretch);
		top_layout.Add(header_title_card).Fit().MinCross(DPI(0));
		{
			auto spacer = top_layout.AddSpacer(1);
			spacer.Fit().MinMain(DPI(10));
			spacer.MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
			spacer.LineEnabled(true).LineOrientation(UiSpacerLineOrientation::Vertical).LineAlign(UiCrossAlign::Start).LineThickness(DPI(2)).LineDash(SOLID).LineInset(DPI(2));
		}
		top_layout.Add(save_split_btn).Fixed(DPI(84)).MinCross(DPI(24)).AlignSelf(UiBoxLayout::Align::Stretch);
		top_layout.Add(export_split_btn).Fixed(DPI(84)).MinCross(DPI(24)).AlignSelf(UiBoxLayout::Align::Stretch);
		top_layout.Add(version_label).Fit().MinMaxCross(DPI(28), DPI(28));
		{
			auto spacer = top_layout.AddSpacer(1);
			spacer.Expand(1).MinMain(DPI(10));
			spacer.MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
			spacer.LineEnabled(true).LineOrientation(UiSpacerLineOrientation::Vertical).LineAlign(UiCrossAlign::End).LineThickness(DPI(2)).LineDash(SOLID).LineInset(DPI(2));
		}
		top_layout.Add(dark_theme_tool).Fit().MinCross(DPI(0));
		top_layout.Add(help_tool).Fit().MinCross(DPI(0));
		top_layout.Add(exit_tool).Fit().MinCross(DPI(0));
		main_window_layout.Add(center_layout).Expand(1).MinCross(DPI(0)).AlignSelf(UiBoxLayout::Align::Stretch);
		center_layout.Add(center_panel).Expand(1).MinCross(DPI(0)).AlignSelf(UiBoxLayout::Align::Stretch);
		center_layout_02.Add(center_tools_panel).Fixed(DPI(63)).MinCross(DPI(0)).AlignSelf(UiBoxLayout::Align::Stretch);
		center_tools_layout.Add(controls_tool).Fit().MinCross(DPI(0));
		center_tools_layout.Add(composites_tool).Fit().MinCross(DPI(0));
		{
			auto spacer = center_tools_layout.AddSpacer(1);
			spacer.Expand(1).MinMain(DPI(75));
			spacer.MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
			spacer.LineEnabled(true).LineOrientation(UiSpacerLineOrientation::Vertical).LineAlign(UiCrossAlign::End).LineThickness(DPI(2)).LineDash(SOLID).LineInset(DPI(0));
		}
		center_tools_layout.Add(theme_selection_drop_down).Fixed(DPI(124)).MinCross(DPI(0)).AlignSelf(UiBoxLayout::Align::Stretch);
		center_tools_layout.Add(button).Fit().MinCross(DPI(0));
		center_tools_layout.Add(button_02).Fit().MinCross(DPI(0));
		center_tools_layout.Add(button_03).Fit().MinCross(DPI(0));
		center_tools_layout.Add(button_04).Fit().MinCross(DPI(0));
		center_layout_02.Add(center_preview_panel).Expand(1).MinCross(DPI(0)).AlignSelf(UiBoxLayout::Align::Stretch);
		boxlayout.Add(panel).Fit().MinCross(DPI(0)).AlignSelf(UiBoxLayout::Align::Stretch);
		boxlayout.Add(lower_grid).Expand(1).MinCross(DPI(0)).AlignSelf(UiBoxLayout::Align::Stretch);
		center_layout.Add(right_layout).Fit().MinCross(DPI(0)).AlignSelf(UiBoxLayout::Align::Stretch);
		right_layout.Add(right_tools_panel).Fixed(DPI(63)).MinMaxCross(DPI(308), DPI(308));
		right_tools_layout.Add(right_open_close_btn).Fit().MinCross(DPI(0));
		right_tools_layout.Add(right_expand_toggle_btn).Fit().MinCross(DPI(0));
		{
			auto spacer = right_tools_layout.AddSpacer(1);
			spacer.Expand(1).MinMain(DPI(75));
			spacer.MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
			spacer.LineEnabled(true).LineOrientation(UiSpacerLineOrientation::Vertical).LineAlign(UiCrossAlign::End).LineThickness(DPI(2)).LineDash(SOLID).LineInset(DPI(0));
		}
		right_tools_layout.Add(hierarchy_tool).Fit().MinCross(DPI(0));
		right_tools_layout.Add(inspector_tool).Fit().MinCross(DPI(0));
		right_tools_layout.Add(overrides_tool).Fit().MinCross(DPI(0));
		right_tools_layout.Add(code_tool).Fit().MinCross(DPI(0));
		right_layout.Add(right_info_panel).Expand(1).MinCross(DPI(0)).AlignSelf(UiBoxLayout::Align::Stretch);
		main_window_layout.Add(lower_layout).Fit().MinCross(DPI(0)).AlignSelf(UiBoxLayout::Align::Stretch);
		lower_layout.Add(lower__label).Fit().MinCross(DPI(0));
	}

	void PostBuild()
	{
		// Active tabs/pages and late setup.
		tab_02.SetActiveTab(0);
	}

	UiBoxLayout main_window_layout;
	UiBoxLayout top_layout;
	UiBoxLayout center_layout;
	UiBoxLayout lower_layout;
	UiTitleCard header_title_card;
	UiSplitButton save_split_btn;
	UiDropdown theme_selection_drop_down;
	UiToolButton help_tool;
	UiLabel lower__label;
	UiLabel version_label;
	UiToolButton dark_theme_tool;
	UiBoxLayout right_layout;
	UiToolButton controls_tool;
	UiToolButton composites_tool;
	UiPanel right_tools_panel;
	UiBoxLayout right_tools_layout;
	UiToolButton code_tool;
	UiToolButton overrides_tool;
	UiToolButton inspector_tool;
	UiToolButton hierarchy_tool;
	UiToolButton right_open_close_btn;
	UiScrollPanel right_info_panel;
	UiPanel center_panel;
	UiBoxLayout center_layout_02;
	UiPanel center_tools_panel;
	UiScrollPanel center_preview_panel;
	UiBoxLayout center_tools_layout;
	UiToolButton right_expand_toggle_btn;
	UiSplitButton export_split_btn;
	UiToolButton exit_tool;
	UiButton button;
	UiButton button_02;
	UiButton button_03;
	UiButton button_04;
	UiBoxLayout boxlayout;
	UiGridLayout lower_grid;
	UiPanel panel;
	UiGridLayout gridlayout;
	UiTitleCard titlecard;
	UiPanel panel_02;
	UiGridLayout gridlayout_02;
	UiLabel label;
	UiLabel label_02;
	UiToggle toggle;
	UiToggle toggle_02;
	UiGroupPanel grouppanel_02;
	UiGridLayout gridlayout_03;
	UiDirectContentHost gridlayout_03_host;
	UiGridLayout gridlayout_04;
	UiGridLayout gridlayout_05;
	UiGroupPanel grouppanel_03;
	UiGroupPanel grouppanel_04;
	UiGroupPanel grouppanel_06;
	UiGroupPanel grouppanel_07;
	UiGroupPanel grouppanel_08;
	UiGridLayout gridlayout_06;
	UiGroupPanel grouppanel_09;
	UiGroupPanel grouppanel_10;
	UiButton button_05;
	UiDirectContentHost button_05_host;
	UiToolButton toolbutton;
	UiDirectContentHost toolbutton_host;
	UiSplitButton splitbutton;
	UiDirectContentHost splitbutton_host;
	UiBreadcrumbs breadcrumbs;
	UiDirectContentHost breadcrumbs_host;
	UiIntEdit intedit;
	UiDirectContentHost intedit_host;
	UiFloatEdit floatedit;
	UiDirectContentHost floatedit_host;
	UiGridLayout gridlayout_07;
	UiGroupPanel grouppanel_03_02;
	UiGroupPanel grouppanel_03_03;
	UiMaskEdit maskedit;
	UiDirectContentHost maskedit_host;
	UiPasswordEdit passwordedit;
	UiDirectContentHost passwordedit_host;
	UiDoc doc;
	UiDirectContentHost doc_host;
	UiGroupPanel grouppanel_11;
	UiGroupPanel grouppanel_12;
	UiTab tab_02;
	UiDirectContentHost tab_02_host;
	ParentCtrl pageA;
	ParentCtrl pageB;
	ParentCtrl pageC;
	UiTree tree;
	UiTable table;
	UiGridLayout gridlayout_09;
	UiDirectContentHost gridlayout_09_host;
	UiAccordion accordion;
	ParentCtrl sectionA;
	ParentCtrl sectionB;
	ParentCtrl sectionC;
	UiGroupPanel grouppanel;
	UiGridLayout gridlayout_08;
	UiDirectContentHost gridlayout_08_host;
	UiProgressBar progressbar;
	UiSlider slider;
};

GUI_APP_MAIN
{
	design_themestudioWindow().Run();
}
