#include "IconExportCore.h"

namespace Upp {

static void AddLE16(StringBuffer& out, unsigned int value)
{
	out.Cat((char)(value & 0xffu));
	out.Cat((char)((value >> 8) & 0xffu));
}

bool ValidateUppImlImageSize(Size sz, String* error)
{
	if(sz.cx <= 0 || sz.cy <= 0) {
		if(error)
			*error = Format("Cannot encode image with invalid size %dx%d.", sz.cx, sz.cy);
		return false;
	}
	if(sz.cx > 0xffff || sz.cy > 0xffff) {
		if(error)
			*error = Format("Cannot encode image with size %dx%d because U++ IML dimensions are uint16.", sz.cx, sz.cy);
		return false;
	}
	return true;
}

bool BuildUppImlPayload(const Image& img, String& payload, String* error)
{
	payload.Clear();
	Size sz = img.GetSize();
	if(!ValidateUppImlImageSize(sz, error))
		return false;

	int64 total = 13 + 4ll * sz.cx * sz.cy;
	if(total <= 13 || total > INT_MAX) {
		if(error)
			*error = Format("Cannot encode image with size %dx%d because the U++ IML payload would overflow.", sz.cx, sz.cy);
		return false;
	}

	StringBuffer raw;
	raw.Reserve((int)total);
	raw.Cat((char)0);
	AddLE16(raw, (unsigned int)sz.cx);
	AddLE16(raw, (unsigned int)sz.cy);
	AddLE16(raw, 0);
	AddLE16(raw, 0);
	AddLE16(raw, 0);
	AddLE16(raw, 0);

	for(int y = 0; y < sz.cy; ++y) {
		const RGBA* row = img[y];
		for(int x = 0; x < sz.cx; ++x) {
			const RGBA& px = row[x];
			raw.Cat((char)px.r);
			raw.Cat((char)px.g);
			raw.Cat((char)px.b);
			raw.Cat((char)px.a);
		}
	}

	payload = ZCompress(String(raw));
	if(payload.IsVoid()) {
		if(error)
			*error = "Could not compress U++ IML payload.";
		return false;
	}
	return true;
}

bool BuildUppImlEntryText(const String& token, const String& compressed, const String& source_svg, Size sz, String& out, String* error)
{
	out.Clear();
	if(token.IsEmpty()) {
		if(error)
			*error = "Cannot emit U++ IML entry without a symbol token.";
		return false;
	}
	if(compressed.IsEmpty()) {
		if(error)
			*error = Format("Cannot emit U++ IML entry '%s' with an empty payload.", token);
		return false;
	}
	if(!ValidateUppImlImageSize(sz, error))
		return false;

	String text;
	text << "// Auto-generated by MakeIconFromSVG\n";
	text << "// Source: " << source_svg << "\n";
	text << "// Size: " << sz.cx << "x" << sz.cy << "\n";
	text << "// Format: U++ IML packed payload\n";
	text << "IMAGE_ID(" << token << ")\n";
	text << "IMAGE_BEGIN_DATA\n";
	for(int i = 0; i < compressed.GetCount(); i += 32) {
		text << "IMAGE_DATA(";
		for(int j = 0; j < 32; ++j) {
			int index = i + j;
			byte b = index < compressed.GetCount() ? (byte)compressed[index] : 0;
			if(j)
				text << ",";
			text << Format("0x%02x", (int)b);
		}
		text << ")\n";
	}
	text << "IMAGE_END_DATA(" << compressed.GetCount() << ", 1)\n";
	out = text;
	return true;
}

bool BuildUppImlEntryText(const String& token, const Image& img, const String& source_svg, String& out, String* error)
{
	String payload;
	if(!BuildUppImlPayload(img, payload, error))
		return false;
	return BuildUppImlEntryText(token, payload, source_svg, img.GetSize(), out, error);
}

}
