// Generated by U++ Ui Designer.
// Designer version: v1.0.0-rc1
// Appearance mode: ThemeFirst
// Source design: design_newlayout.json
// Package: design_newlayout
// UMK path: E:\upp-18468\umk.exe
// Exported package: E:\apps\github\upp_Ui\designs\DesignerExport
// Build method: CLANGx64
// Output executable: [PATH_TO_OUTPUT_EXE]
// Regenerate from design.json when the Designer model changes.
// This file is theme-first generated output.
// Explicit Designer appearance overrides are marked in code.

#include <CtrlLib/CtrlLib.h>
#include <Ui/Ui.h>

using namespace Upp;

// -----------------------------------------------------------------------------
// Theme candidates
// -----------------------------------------------------------------------------
// Designer appearance export omitted in theme-first mode.
// Instance-specific text, layout, data, and event wiring remain outside this section.

class design_newlayoutWindow : public TopWindow {
public:
	typedef design_newlayoutWindow CLASSNAME;

	design_newlayoutWindow()
	{
		InitWindow();
		InitThemeContext();
		BuildControls();
		ApplyAppearanceOverrides();
		BuildLayout();
		PostBuild();
	}

private:
	void InitWindow()
	{
		Title("Generated Designer Layout");
		Sizeable().Zoomable();
		SetRect(0, 0, DPI(1020), DPI(668));
	}

	void InitThemeContext()
	{
		// Move this method to GeneratedDesignerTheme.cpp if splitting the generated app.
		// Theme context / preset setup.
	}

	void BuildControls()
	{
		// Control text, icons, values, ranges, roles, and basic behaviour.
		main_window_layout.SetDirection(UiDirection::V).SetGap(DPI(8), DPI(0)).SetInset(DPI(0)).SetWrap(UiBoxWrap::None);
		top_layout.SetDirection(UiDirection::H).SetGap(DPI(8), DPI(8)).SetInset(DPI(6)).SetWrap(UiBoxWrap::Flow).SetWrapAutoResize(true);
		center_layout.SetDirection(UiDirection::H).SetGap(DPI(0), DPI(0)).SetInset(DPI(1)).SetWrap(UiBoxWrap::None);
		lower_layout.SetDirection(UiDirection::V).SetGap(DPI(8), DPI(8)).SetInset(DPI(0)).SetWrap(UiBoxWrap::None);
		header_title_card.SetCustomStyle(UiTheme::ResolveTitleCard(UiRole::Accent));
		header_title_card.SetTitle("Designer").SetSubTitle("").SetContentInset(DPI(4)).SetMediaGap(DPI(9)).SetMediaReserve(DPI(0)).SetMediaMin(DPI(15)).SetMediaAutoFit(false).SetMediaSide(UiAlign::LEFT).SetMediaAlign(UiAlign::CENTER, UiAlign::CENTER).ShowTitleLine(false).ShowCardLine(false);
		header_title_card.SetMedia(ICON_BRAND_NEWLOGO_V5_48(), Size(DPI(18), DPI(18)));
		save_split_btn.SetCustomStyle(UiTheme::ResolveButton(UiRole::Accent));
		save_split_btn.SetMinSize(Size(DPI(74), DPI(24)));
		save_split_btn.SetText("Save").SetContentInset(DPI(6)).SetContentGap(DPI(6));
		save_split_btn.SetSplitWidth(DPI(31));
		save_split_btn.SetSplitContentGap(DPI(4));
		save_split_btn.SetSplitIconSize(DPI(10));
		save_split_btn.SetPopupMinWidth(DPI(220));
		save_split_btn.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		save_split_btn.SetIconSide(UiAlign::LEFT);
		save_split_btn.Add("Recent A", "a").Add("Recent B", "b").Add("Recent C", "c");
		load_split_btn.SetCustomStyle(UiTheme::ResolveButton(UiRole::Accent));
		load_split_btn.SetMinSize(Size(DPI(74), DPI(24)));
		load_split_btn.SetText("Load").SetContentInset(DPI(2)).SetContentGap(DPI(4));
		load_split_btn.SetSplitWidth(DPI(30));
		load_split_btn.SetSplitContentGap(DPI(4));
		load_split_btn.SetSplitIconSize(DPI(10));
		load_split_btn.SetPopupMinWidth(DPI(220));
		load_split_btn.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		load_split_btn.SetIconSide(UiAlign::LEFT);
		load_split_btn.Add("Recent A", "a").Add("Recent B", "b").Add("Recent C", "c");
		theme_selection_drop_down.SetCustomStyle(UiTheme::ResolveDropdown(UiRole::Subtle));
		theme_selection_drop_down.SetMinSize(Size(DPI(74), DPI(0)));
		theme_selection_drop_down.UseInternalModel().Clear().Add("Theme", "Theme");
		theme_selection_drop_down.Select(0);
		theme_selection_drop_down.SetIndicatorSide(UiAlign::RIGHT);
		theme_selection_drop_down.SetIndicatorSize(DPI(14));
		help_tool.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Accent));
		help_tool.SetMinSize(Size(DPI(60), DPI(0)));
		help_tool.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		help_tool.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		help_tool.SetIconSide(UiAlign::LEFT);
		help_tool.SetIcon(ICON_DESIGN_HELP_48()).SetIconSize(DPI(16), DPI(16));
		lower__label.SetText("Label");
		lower__label.SetAlign(UiAlign::LEFT, UiAlign::CENTER);
		lower__label.SetIconSide(UiAlign::LEFT);
		lower__label.SetContentGap(DPI(6));
		lower__label.SetIconScaleToContent(false);
		version_label.SetCustomStyle(UiTheme::ResolveLabel(UiRole::Accent));
		version_label.SetMinSize(Size(DPI(76), DPI(28)));
		version_label.SetText("v2.3.1");
		version_label.SetAlign(UiAlign::LEFT, UiAlign::CENTER);
		version_label.SetIconSide(UiAlign::LEFT);
		version_label.SetContentGap(DPI(5));
		version_label.SetIconScaleToContent(false);
		version_label.SetIcon(ICON_DESIGN_ADJUST_48(), UiIconRenderMode::MonoTint).SetIconSize(DPI(10), DPI(10));
		dark_theme_tool.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Accent));
		dark_theme_tool.SetMinSize(Size(DPI(60), DPI(0)));
		dark_theme_tool.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		dark_theme_tool.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		dark_theme_tool.SetIconSide(UiAlign::LEFT);
		dark_theme_tool.SetIcon(ICON_ACTION_DARK_MODE_48()).SetIconSize(DPI(16), DPI(16));
		leftlayout.SetMinSize(Size(DPI(56), DPI(1)));
		leftlayout.SetDirection(UiDirection::V).SetGap(DPI(0), DPI(0)).SetInset(DPI(0)).SetWrap(UiBoxWrap::Flow).SetWrapAutoResize(true);
		rightlayout.SetDirection(UiDirection::V).SetGap(DPI(0), DPI(0)).SetInset(DPI(0)).SetWrap(UiBoxWrap::Flow).SetWrapAutoResize(true);
		layouts_tool.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		layouts_tool.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		layouts_tool.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		layouts_tool.SetIconSide(UiAlign::LEFT);
		layouts_tool.SetIcon(ICON_DESIGN_LAYOUTS_CATEGORY_48()).SetIconSize(DPI(16), DPI(16));
		layouts_tool.Tip("Layouts");
		containers_tool.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		containers_tool.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		containers_tool.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		containers_tool.SetIconSide(UiAlign::LEFT);
		containers_tool.SetIcon(ICON_DESIGN_TAB_GROUP_48()).SetIconSize(DPI(16), DPI(16));
		containers_tool.Tip("Containers");
		controls_tool.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		controls_tool.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		controls_tool.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		controls_tool.SetIconSide(UiAlign::LEFT);
		controls_tool.SetIcon(ICON_DESIGN_WIDGETS_48()).SetIconSize(DPI(16), DPI(16));
		controls_tool.Tip("Controls");
		composites_tool.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		composites_tool.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		composites_tool.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		composites_tool.SetIconSide(UiAlign::LEFT);
		composites_tool.SetIcon(ICON_DESIGN_DYNAMIC_FORM_48()).SetIconSize(DPI(16), DPI(16));
		composites_tool.Tip("Composites");
		presets_tool.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		presets_tool.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		presets_tool.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		presets_tool.SetIconSide(UiAlign::LEFT);
		presets_tool.SetIcon(ICON_DESIGN_DASHBOARD_EDIT_48()).SetIconSize(DPI(16), DPI(16));
		presets_tool.Tip("Presets");
		open_close_lift_panel.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		open_close_lift_panel.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		open_close_lift_panel.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		open_close_lift_panel.SetIconSide(UiAlign::LEFT);
		open_close_lift_panel.SetIcon(ICON_DESIGN_LEFT_PANEL_CLOSE_48()).SetIconSize(DPI(16), DPI(16));
		left_info_panel.SetMinSize(Size(DPI(0), DPI(1)));
		left_info_panel.SetInset(DPI(0));
		left_info_panel.SetScrollMode(UIPANELSCROLL_AUTO);
		left_tools_panel.SetCustomStyle(UiTheme::ResolvePanel(UiRole::Subtle));
		left_tools_panel.SetSizeMin(DPI(0), DPI(0));
		left_tools_panel.SetInset(DPI(0));
		left_tools_layout.SetDirection(UiDirection::H).SetGap(DPI(8), DPI(8)).SetInset(DPI(20)).SetWrap(UiBoxWrap::None);
		right_tools_panel.SetCustomStyle(UiTheme::ResolvePanel(UiRole::Subtle));
		right_tools_panel.SetSizeMin(DPI(0), DPI(0));
		right_tools_panel.SetInset(DPI(0));
		right_tools_layout.SetDirection(UiDirection::H).SetGap(DPI(8), DPI(8)).SetInset(DPI(19)).SetWrap(UiBoxWrap::None);
		code_tool.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		code_tool.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		code_tool.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		code_tool.SetIconSide(UiAlign::LEFT);
		code_tool.SetIcon(ICON_DESIGN_CODE_BLOCKS_48()).SetIconSize(DPI(16), DPI(16));
		code_tool.Tip("Code");
		overrides_tool.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		overrides_tool.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		overrides_tool.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		overrides_tool.SetIconSide(UiAlign::LEFT);
		overrides_tool.SetIcon(ICON_DESIGN_FORMAT_PAINT_48()).SetIconSize(DPI(16), DPI(16));
		overrides_tool.Tip("Theme Overrides ");
		inspector_tool.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		inspector_tool.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		inspector_tool.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		inspector_tool.SetIconSide(UiAlign::LEFT);
		inspector_tool.SetIcon(ICON_DESIGN_TUNE_48()).SetIconSize(DPI(16), DPI(16));
		inspector_tool.Tip("Inspector ");
		hierarchy_tool.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		hierarchy_tool.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		hierarchy_tool.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		hierarchy_tool.SetIconSide(UiAlign::LEFT);
		hierarchy_tool.SetIcon(ICON_DESIGN_ACCOUNT_TREE_48()).SetIconSize(DPI(16), DPI(16));
		hierarchy_tool.Tip("Hierarchy tree");
		right_open_close_btn.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		right_open_close_btn.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		right_open_close_btn.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		right_open_close_btn.SetIconSide(UiAlign::LEFT);
		right_open_close_btn.SetIcon(ICON_DESIGN_RIGHT_PANEL_CLOSE_48()).SetIconSize(DPI(16), DPI(16));
		right_info_panel.SetMinSize(Size(DPI(0), DPI(1)));
		right_info_panel.SetInset(DPI(0));
		right_info_panel.SetScrollMode(UIPANELSCROLL_AUTO);
		exit_tool.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Alert));
		exit_tool.SetMinSize(Size(DPI(60), DPI(0)));
		exit_tool.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		exit_tool.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		exit_tool.SetIconSide(UiAlign::LEFT);
		exit_tool.SetIcon(ICON_DESIGN_MODE_OFF_ON_48()).SetIconSize(DPI(16), DPI(16));
		center_panel.SetCustomStyle(UiTheme::ResolvePanel(UiRole::Subtle));
		center_panel.SetSizeMin(DPI(0), DPI(0));
		center_panel.SetInset(DPI(0));
		center_box_layout.SetDirection(UiDirection::V).SetGap(DPI(0), DPI(0)).SetInset(DPI(0)).SetWrap(UiBoxWrap::None);
		zoom_aspect_panel.SetCustomStyle(UiTheme::ResolvePanel(UiRole::Subtle));
		zoom_aspect_panel.SetSizeMin(DPI(0), DPI(0));
		zoom_aspect_panel.SetInset(DPI(0));
		zoom_aspect_panel.Tip("Set size or aspect ratio");
		preview_panel.SetCustomStyle(UiTheme::ResolveScrollPanel(UiRole::Subtle));
		preview_panel.SetInset(DPI(0));
		preview_panel.SetScrollMode(UIPANELSCROLL_AUTO);
		zoom_aspect_layout.SetDirection(UiDirection::H).SetGap(DPI(8), DPI(8)).SetInset(DPI(19)).SetWrap(UiBoxWrap::None);
		portrait_aspect.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		portrait_aspect.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		portrait_aspect.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		portrait_aspect.SetIconSide(UiAlign::LEFT);
		portrait_aspect.SetIcon(ICON_DESIGN_SPLITSCREEN_PORTRAIT_48()).SetIconSize(DPI(20), DPI(20));
		portrait_aspect.Tip("Portrait ");
		landscape_aspect.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		landscape_aspect.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		landscape_aspect.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		landscape_aspect.SetIconSide(UiAlign::LEFT);
		landscape_aspect.SetIcon(ICON_DESIGN_SPLITSCREEN_LANDSCAPE_48()).SetIconSize(DPI(20), DPI(20));
		landscape_aspect.Tip("Landscape ");
		preset_saspect.SetCustomStyle(UiTheme::ResolveButton(UiRole::Subtle));
		preset_saspect.SetMinSize(Size(DPI(60), DPI(0)));
		preset_saspect.SetText("2:1").SetContentInset(DPI(6)).SetContentGap(DPI(4));
		preset_saspect.SetSplitWidth(DPI(30));
		preset_saspect.SetSplitContentGap(DPI(4));
		preset_saspect.SetSplitIconSize(DPI(16));
		preset_saspect.SetPopupMinWidth(DPI(220));
		preset_saspect.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		preset_saspect.SetIconSide(UiAlign::LEFT);
		preset_saspect.Add("Portrait 1:2 ", "a").Add(" Landscape 2:1", "b").Add(" Square 1:1", "c");
		preset_saspect.Tip("Preset Aspect");
		square_aspect.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		square_aspect.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		square_aspect.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		square_aspect.SetIconSide(UiAlign::LEFT);
		square_aspect.SetIcon(ICON_TOGGLE_CHECK_BOX_OUTLINE_BLANK_48()).SetIconSize(DPI(17), DPI(17));
		square_aspect.Tip("Square");
		right_expand_toggle_btn.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		right_expand_toggle_btn.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		right_expand_toggle_btn.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		right_expand_toggle_btn.SetIconSide(UiAlign::LEFT);
		right_expand_toggle_btn.SetIcon(ICON_DESIGN_UNFOLD_MORE_48()).SetIconSize(DPI(16), DPI(16));
		right_expand_toggle_btn.Tip("Expand toggle");
		theme_studio_button.SetCustomStyle(UiTheme::ResolveButton(UiRole::Alert));
		theme_studio_button.SetText("Theme Studio").SetContentInset(DPI(6)).SetContentGap(DPI(4));
		theme_studio_button.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		theme_studio_button.SetIconSide(UiAlign::LEFT);
		theme_studio_button.Tip("Theme Studio");
		export_split_btn.SetCustomStyle(UiTheme::ResolveButton(UiRole::Accent));
		export_split_btn.SetMinSize(Size(DPI(74), DPI(24)));
		export_split_btn.SetText("Export").SetContentInset(DPI(6)).SetContentGap(DPI(6));
		export_split_btn.SetSplitWidth(DPI(31));
		export_split_btn.SetSplitContentGap(DPI(4));
		export_split_btn.SetSplitIconSize(DPI(10));
		export_split_btn.SetPopupMinWidth(DPI(220));
		export_split_btn.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		export_split_btn.SetIconSide(UiAlign::LEFT);
		export_split_btn.Add("Header/Cpp", "a").Add("Cpp (Main)", "b").Add("Theam (only)", "c");
	}

	void ApplyAppearanceOverrides()
	{
		// Designer appearance export omitted; theme-first output only.
	}

	void BuildLayout()
	{
		// Parent-child layout tree only.
		Add(main_window_layout);
		main_window_layout.Add(top_layout).Fit().MinCross(DPI(0)).AlignSelf(UiBoxLayout::Align::Stretch);
		top_layout.Add(header_title_card).Fit().MinCross(DPI(0));
		{
			auto spacer = top_layout.AddSpacer(1);
			spacer.Fit().MinMain(DPI(10));
			spacer.MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
			spacer.LineEnabled(true).LineOrientation(UiSpacerLineOrientation::Vertical).LineAlign(UiCrossAlign::Start).LineThickness(DPI(2)).LineDash(SOLID).LineInset(DPI(2));
		}
		top_layout.Add(save_split_btn).Fixed(DPI(84)).MinCross(DPI(24)).AlignSelf(UiBoxLayout::Align::Stretch);
		top_layout.Add(export_split_btn).Fixed(DPI(84)).MinCross(DPI(24)).AlignSelf(UiBoxLayout::Align::Stretch);
		top_layout.Add(load_split_btn).Fixed(DPI(84)).MinCross(DPI(24)).AlignSelf(UiBoxLayout::Align::Stretch);
		top_layout.Add(version_label).Fit().MinMaxCross(DPI(28), DPI(28));
		{
			auto spacer = top_layout.AddSpacer(1);
			spacer.Expand(1).MinMain(DPI(10));
			spacer.MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
			spacer.LineEnabled(true).LineOrientation(UiSpacerLineOrientation::Vertical).LineAlign(UiCrossAlign::End).LineThickness(DPI(2)).LineDash(SOLID).LineInset(DPI(2));
		}
		top_layout.Add(theme_studio_button).Fit().MinCross(DPI(0));
		top_layout.Add(dark_theme_tool).Fit().MinCross(DPI(0));
		top_layout.Add(help_tool).Fit().MinCross(DPI(0));
		top_layout.Add(exit_tool).Fit().MinCross(DPI(0));
		main_window_layout.Add(center_layout).Expand(1).MinCross(DPI(0)).AlignSelf(UiBoxLayout::Align::Stretch);
		center_layout.Add(leftlayout).Fit().MinCross(DPI(1)).AlignSelf(UiBoxLayout::Align::Stretch);
		leftlayout.Add(left_tools_panel).Fixed(DPI(63)).MinCross(DPI(0));
		left_tools_layout.Add(layouts_tool).Fit().MinCross(DPI(0));
		left_tools_layout.Add(containers_tool).Fit().MinCross(DPI(0));
		left_tools_layout.Add(controls_tool).Fit().MinCross(DPI(0));
		left_tools_layout.Add(composites_tool).Fit().MinCross(DPI(0));
		left_tools_layout.Add(presets_tool).Fit().MinCross(DPI(0));
		{
			auto spacer = left_tools_layout.AddSpacer(1);
			spacer.Expand(1).MinMain(DPI(28));
			spacer.MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
			spacer.LineEnabled(true).LineOrientation(UiSpacerLineOrientation::Vertical).LineAlign(UiCrossAlign::Start).LineThickness(DPI(2)).LineDash(SOLID).LineInset(DPI(0));
		}
		left_tools_layout.Add(open_close_lift_panel).Fit().MinCross(DPI(0));
		leftlayout.Add(left_info_panel).Expand(1).MinCross(DPI(0)).AlignSelf(UiBoxLayout::Align::Stretch);
		center_layout.Add(center_panel).Expand(1).MinCross(DPI(0)).AlignSelf(UiBoxLayout::Align::Stretch);
		center_box_layout.Add(zoom_aspect_panel).Fixed(DPI(63)).MinMaxCross(DPI(340), DPI(340));
		zoom_aspect_layout.Add(portrait_aspect).Fit().MinCross(DPI(0));
		zoom_aspect_layout.Add(landscape_aspect).Fit().MinCross(DPI(0));
		zoom_aspect_layout.Add(square_aspect).Fit().MinCross(DPI(0));
		zoom_aspect_layout.Add(preset_saspect).Fit().MinCross(DPI(0));
		zoom_aspect_layout.Add(theme_selection_drop_down).Fixed(DPI(84)).MinCross(DPI(0)).AlignSelf(UiBoxLayout::Align::Stretch);
		center_box_layout.Add(preview_panel).Expand(1).MinCross(DPI(0)).AlignSelf(UiBoxLayout::Align::Stretch);
		center_layout.Add(rightlayout).Fit().MinCross(DPI(0)).AlignSelf(UiBoxLayout::Align::Stretch);
		rightlayout.Add(right_tools_panel).Fixed(DPI(63)).MinMaxCross(DPI(346), DPI(346));
		right_tools_layout.Add(right_open_close_btn).Fit().MinCross(DPI(0));
		right_tools_layout.Add(right_expand_toggle_btn).Fit().MinCross(DPI(0));
		{
			auto spacer = right_tools_layout.AddSpacer(1);
			spacer.Expand(1).MinMain(DPI(75));
			spacer.MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
			spacer.LineEnabled(true).LineOrientation(UiSpacerLineOrientation::Vertical).LineAlign(UiCrossAlign::End).LineThickness(DPI(2)).LineDash(SOLID).LineInset(DPI(0));
		}
		right_tools_layout.Add(hierarchy_tool).Fit().MinCross(DPI(0));
		right_tools_layout.Add(inspector_tool).Fit().MinCross(DPI(0));
		right_tools_layout.Add(overrides_tool).Fit().MinCross(DPI(0));
		right_tools_layout.Add(code_tool).Fit().MinCross(DPI(0));
		rightlayout.Add(right_info_panel).Expand(1).MinCross(DPI(0)).AlignSelf(UiBoxLayout::Align::Stretch);
		main_window_layout.Add(lower_layout).Fit().MinCross(DPI(0)).AlignSelf(UiBoxLayout::Align::Stretch);
		lower_layout.Add(lower__label).Fit().MinCross(DPI(0));
	}

	void PostBuild()
	{
		// Active tabs/pages and late setup.
	}

	UiBoxLayout main_window_layout;
	UiBoxLayout top_layout;
	UiBoxLayout center_layout;
	UiBoxLayout lower_layout;
	UiTitleCard header_title_card;
	UiSplitButton save_split_btn;
	UiSplitButton load_split_btn;
	UiDropdown theme_selection_drop_down;
	UiToolButton help_tool;
	UiLabel lower__label;
	UiLabel version_label;
	UiToolButton dark_theme_tool;
	UiBoxLayout leftlayout;
	UiBoxLayout rightlayout;
	UiToolButton layouts_tool;
	UiToolButton containers_tool;
	UiToolButton controls_tool;
	UiToolButton composites_tool;
	UiToolButton presets_tool;
	UiToolButton open_close_lift_panel;
	UiScrollPanel left_info_panel;
	UiPanel left_tools_panel;
	UiBoxLayout left_tools_layout;
	UiPanel right_tools_panel;
	UiBoxLayout right_tools_layout;
	UiToolButton code_tool;
	UiToolButton overrides_tool;
	UiToolButton inspector_tool;
	UiToolButton hierarchy_tool;
	UiToolButton right_open_close_btn;
	UiScrollPanel right_info_panel;
	UiToolButton exit_tool;
	UiPanel center_panel;
	UiBoxLayout center_box_layout;
	UiPanel zoom_aspect_panel;
	UiScrollPanel preview_panel;
	UiBoxLayout zoom_aspect_layout;
	UiToolButton portrait_aspect;
	UiToolButton landscape_aspect;
	UiSplitButton preset_saspect;
	UiToolButton square_aspect;
	UiToolButton right_expand_toggle_btn;
	UiButton theme_studio_button;
	UiSplitButton export_split_btn;
};

GUI_APP_MAIN
{
	design_newlayoutWindow().Run();
}
