// Generated by U++ Ui Designer.
// Source design: design_designer.json
// Package: DesignerExportSmoke
// UMK path: E:\upp-18468\umk.exe
// Exported package: E:\apps\github\upp_Ui\DesignerExportSmoke
// Build method: CLANGx64
// Output executable: E:\apps\github\upp_Ui\out\DesignerExportSmoke.exe
// Regenerate from design.json when the Designer model changes.
// This file is theme-first generated output.
// Explicit Designer appearance overrides are marked in code.
#include <CtrlLib/CtrlLib.h>
#include <Ui/Ui.h>
using namespace Upp;
class DesignerExportSmokeWindow : public TopWindow {
public:
	typedef DesignerExportSmokeWindow CLASSNAME;
	DesignerExportSmokeWindow()
	{
		Title("Generated Designer Layout");
		Sizeable().Zoomable();
		SetRect(0, 0, DPI(760), DPI(460));
		Build();
	}
private:
	void Build()
	{
		// Control setup.
		main_box.SetDirection(UiDirection::V).SetGap(DPI(8), DPI(8)).SetInset(DPI(8)).SetWrap(UiBoxWrap::None);
		top_box.SetDirection(UiDirection::H).SetGap(DPI(8), DPI(8)).SetInset(DPI(6)).SetWrap(UiBoxWrap::Flow).SetWrapAutoResize(true);
		titlecard.SetTitle("Designer").SetSubTitle("Workbench shell preset").SetContentInset(DPI(8)).SetMediaGap(DPI(8)).SetMediaReserve(DPI(28)).SetMediaMin(DPI(16)).SetMediaAutoFit(false).SetMediaSide(UiAlign::LEFT).SetMediaAlign(UiAlign::CENTER, UiAlign::CENTER);
		titlecard.SetMedia(ICON_BRAND_NEWLOGO_V5_48(), Size(DPI(18), DPI(18)));
		save_button.SetCustomStyle(UiTheme::ResolveButton(UiRole::Accent));
		save_button.SetMinSize(Size(DPI(10), DPI(24)));
		save_button.SetText("Save").SetContentInset(DPI(6)).SetContentGap(DPI(4));
		save_button.SetSplitWidth(DPI(30));
		save_button.SetSplitContentGap(DPI(4));
		save_button.SetSplitIconSize(DPI(16));
		save_button.SetPopupMinWidth(DPI(220));
		save_button.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		save_button.SetIconSide(UiAlign::LEFT);
		save_button.Add("Recent A", "a").Add("Recent B", "b").Add("Recent C", "c");
		load_button.SetCustomStyle(UiTheme::ResolveButton(UiRole::Accent));
		load_button.SetMinSize(Size(DPI(10), DPI(24)));
		load_button.SetText("Load").SetContentInset(DPI(6)).SetContentGap(DPI(4));
		load_button.SetSplitWidth(DPI(30));
		load_button.SetSplitContentGap(DPI(4));
		load_button.SetSplitIconSize(DPI(16));
		load_button.SetPopupMinWidth(DPI(220));
		load_button.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		load_button.SetIconSide(UiAlign::LEFT);
		load_button.Add("Recent A", "a").Add("Recent B", "b").Add("Recent C", "c");
		version_badge.SetCustomStyle(UiTheme::ResolveLabel(UiRole::Accent));
		version_badge.SetMinSize(Size(DPI(76), DPI(28)));
		version_badge.SetText("v1.0.1 Alpha");
		version_badge.SetAlign(UiAlign::LEFT, UiAlign::CENTER);
		version_badge.SetIconSide(UiAlign::LEFT);
		version_badge.SetContentGap(DPI(6));
		version_badge.SetIconScaleToContent(false);
		version_badge.SetIcon(ICON_DESIGN_ADJUST_48(), UiIconRenderMode::MonoTint).SetIconSize(DPI(18), DPI(18));
		theme_dropdown.SetCustomStyle(UiTheme::ResolveDropdown(UiRole::Accent));
		theme_dropdown.UseInternalModel().Clear().Add("First", "First");
		theme_dropdown.Select(0);
		theme_dropdown.SetIndicatorSide(UiAlign::RIGHT);
		theme_dropdown.SetIndicatorSize(DPI(14));
		dark_toggle.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Accent));
		dark_toggle.SetMinSize(Size(DPI(65), DPI(24)));
		dark_toggle.SetText("Dark").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		dark_toggle.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		dark_toggle.SetIconSide(UiAlign::LEFT);
		dark_toggle.SetIcon(ICON_ACTION_DARK_MODE_48()).SetIconSize(DPI(20), DPI(20));
		help_button.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Accent));
		help_button.SetMinSize(Size(DPI(65), DPI(24)));
		help_button.SetText("Help").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		help_button.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		help_button.SetIconSide(UiAlign::LEFT);
		help_button.SetIcon(ICON_DESIGN_HELP_48()).SetIconSize(DPI(20), DPI(20));
		exit_button.SetCustomStyle(UiTheme::ResolveButton(UiRole::Alert));
		exit_button.SetText("Exit").SetContentInset(DPI(6)).SetContentGap(DPI(4));
		exit_button.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		exit_button.SetIconSide(UiAlign::LEFT);
		exit_button.SetIcon(ICON_ACTION_CANCEL_48()).SetIconSize(DPI(18), DPI(18));
		center_box.SetDirection(UiDirection::H).SetGap(DPI(8), DPI(8)).SetInset(DPI(8)).SetWrap(UiBoxWrap::None);
		leftlayout.SetMinSize(Size(DPI(56), DPI(10)));
		leftlayout.SetDirection(UiDirection::V).SetGap(DPI(8), DPI(8)).SetInset(DPI(8)).SetWrap(UiBoxWrap::Flow).SetWrapAutoResize(true);
		left_tools_panel.SetCustomStyle(UiTheme::ResolvePanel(UiRole::Subtle));
		left_tools_panel.SetSizeMin(DPI(10), DPI(10));
		left_tools.SetDirection(UiDirection::H).SetGap(DPI(8), DPI(8)).SetInset(DPI(8)).SetWrap(UiBoxWrap::Flow).SetWrapAutoResize(true);
		tool.SetText("tool").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		tool.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		tool.SetIconSide(UiAlign::LEFT);
		tool.SetIcon(ICON_DESIGN_LAYOUTS_CATEGORY_48()).SetIconSize(DPI(20), DPI(20));
		tool_02.SetText("tool").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		tool_02.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		tool_02.SetIconSide(UiAlign::LEFT);
		tool_02.SetIcon(ICON_DESIGN_TAB_GROUP_48()).SetIconSize(DPI(20), DPI(20));
		tool_03.SetText("tool").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		tool_03.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		tool_03.SetIconSide(UiAlign::LEFT);
		tool_03.SetIcon(ICON_DESIGN_WIDGETS_48()).SetIconSize(DPI(20), DPI(20));
		tool_04.SetText("tool").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		tool_04.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		tool_04.SetIconSide(UiAlign::LEFT);
		tool_04.SetIcon(ICON_DESIGN_DYNAMIC_FORM_48()).SetIconSize(DPI(20), DPI(20));
		tool_05.SetText("tool").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		tool_05.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		tool_05.SetIconSide(UiAlign::LEFT);
		tool_05.SetIcon(ICON_DESIGN_DASHBOARD_EDIT_48()).SetIconSize(DPI(20), DPI(20));
		close_left.SetText("Close").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		close_left.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		close_left.SetIconSide(UiAlign::LEFT);
		close_left.SetIcon(ICON_DESIGN_LEFT_PANEL_CLOSE_48()).SetIconSize(DPI(20), DPI(20));
		scrollpanel.SetScrollMode(UIPANELSCROLL_AUTO);
		left_scroll_content.SetDirection(UiDirection::V).SetGap(DPI(8), DPI(8)).SetInset(DPI(8)).SetWrap(UiBoxWrap::None);
		Toolbox.SetCustomStyle(UiTheme::ResolveTitleCard(UiRole::Accent));
		Toolbox.SetTitle("Toolbox").SetSubTitle("Pinned tools and categories").SetContentInset(DPI(8)).SetMediaGap(DPI(10)).SetMediaReserve(DPI(24)).SetMediaMin(DPI(16)).SetMediaAutoFit(false).SetMediaSide(UiAlign::LEFT).SetMediaAlign(UiAlign::CENTER, UiAlign::CENTER);
		Library_1.SetTitle("Library 1").SetSubTitle("Reusable assets and fragments").SetContentInset(DPI(8)).SetMediaGap(DPI(10)).SetMediaReserve(DPI(24)).SetMediaMin(DPI(16)).SetMediaAutoFit(false).SetMediaSide(UiAlign::LEFT).SetMediaAlign(UiAlign::CENTER, UiAlign::CENTER);
		Library_2.SetTitle("Library 2").SetSubTitle("Reusable assets and fragments").SetContentInset(DPI(8)).SetMediaGap(DPI(10)).SetMediaReserve(DPI(24)).SetMediaMin(DPI(16)).SetMediaAutoFit(false).SetMediaSide(UiAlign::LEFT).SetMediaAlign(UiAlign::CENTER, UiAlign::CENTER);
		Library_3.SetTitle("Library 3").SetSubTitle("Reusable assets and fragments").SetContentInset(DPI(8)).SetMediaGap(DPI(10)).SetMediaReserve(DPI(24)).SetMediaMin(DPI(16)).SetMediaAutoFit(false).SetMediaSide(UiAlign::LEFT).SetMediaAlign(UiAlign::CENTER, UiAlign::CENTER);
		previewlayout.SetDirection(UiDirection::V).SetGap(DPI(8), DPI(8)).SetInset(DPI(8)).SetWrap(UiBoxWrap::None);
		Preview.SetTitle("Preview").SetSubTitle("Central work area and generated output surface").SetContentInset(DPI(8)).SetMediaGap(DPI(10)).SetMediaReserve(DPI(24)).SetMediaMin(DPI(16)).SetMediaAutoFit(false).SetMediaSide(UiAlign::LEFT).SetMediaAlign(UiAlign::CENTER, UiAlign::CENTER);
		Preview.SetMedia(ICON_DESIGN_PANEL_48(), Size(DPI(18), DPI(18)));
		preview_surface.SetSizeMin(DPI(10), DPI(10));
		preview_stack.SetDirection(UiDirection::V).SetGap(DPI(8), DPI(8)).SetInset(DPI(8)).SetWrap(UiBoxWrap::None);
		Canvas.SetCustomStyle(UiTheme::ResolveTitleCard(UiRole::Subtle));
		Canvas.SetTitle("Canvas").SetSubTitle("Preview frame, selection overlays, and generated shell").SetContentInset(DPI(8)).SetMediaGap(DPI(10)).SetMediaReserve(DPI(24)).SetMediaMin(DPI(16)).SetMediaAutoFit(false).SetMediaSide(UiAlign::LEFT).SetMediaAlign(UiAlign::CENTER, UiAlign::CENTER);
		notes.SetCustomStyle(UiTheme::ResolveLabel(UiRole::Subtle));
		notes.SetText("Resize, theme, save/load, and codegen are all exercised by this preset.");
		notes.SetAlign(UiAlign::LEFT, UiAlign::CENTER);
		notes.SetIconSide(UiAlign::LEFT);
		notes.SetContentGap(DPI(6));
		notes.SetIconScaleToContent(false);
		rightlayout.SetDirection(UiDirection::V).SetGap(DPI(8), DPI(8)).SetInset(DPI(8)).SetWrap(UiBoxWrap::Flow).SetWrapAutoResize(true);
		right_tools_panel.SetCustomStyle(UiTheme::ResolvePanel(UiRole::Subtle));
		right_tools_panel.SetSizeMin(DPI(10), DPI(10));
		right_tools.SetDirection(UiDirection::H).SetGap(DPI(8), DPI(8)).SetInset(DPI(8)).SetWrap(UiBoxWrap::Flow).SetWrapAutoResize(true);
		close_right.SetText("Close").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		close_right.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		close_right.SetIconSide(UiAlign::LEFT);
		close_right.SetIcon(ICON_DESIGN_RIGHT_PANEL_CLOSE_48()).SetIconSize(DPI(20), DPI(20));
		tool_06.SetText("tool").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		tool_06.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		tool_06.SetIconSide(UiAlign::LEFT);
		tool_06.SetIcon(ICON_DESIGN_CODE_BLOCKS_48()).SetIconSize(DPI(20), DPI(20));
		tool_07.SetText("tool").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		tool_07.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		tool_07.SetIconSide(UiAlign::LEFT);
		tool_07.SetIcon(ICON_DESIGN_FORMAT_PAINT_48()).SetIconSize(DPI(20), DPI(20));
		tool_08.SetText("tool").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		tool_08.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		tool_08.SetIconSide(UiAlign::LEFT);
		tool_08.SetIcon(ICON_DESIGN_TUNE_48()).SetIconSize(DPI(20), DPI(20));
		tool_09.SetText("tool").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		tool_09.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		tool_09.SetIconSide(UiAlign::LEFT);
		tool_09.SetIcon(ICON_DESIGN_ACCOUNT_TREE_48()).SetIconSize(DPI(20), DPI(20));
		scrollpanel_02.SetScrollMode(UIPANELSCROLL_AUTO);
		right_scroll_content.SetDirection(UiDirection::V).SetGap(DPI(8), DPI(8)).SetInset(DPI(8)).SetWrap(UiBoxWrap::None);
		Inspector.SetCustomStyle(UiTheme::ResolveTitleCard(UiRole::Accent));
		Inspector.SetTitle("Inspector").SetSubTitle("Properties, code, hierarchy, and theme overrides").SetContentInset(DPI(8)).SetMediaGap(DPI(10)).SetMediaReserve(DPI(24)).SetMediaMin(DPI(16)).SetMediaAutoFit(false).SetMediaSide(UiAlign::LEFT).SetMediaAlign(UiAlign::CENTER, UiAlign::CENTER);
		Panel_1.SetTitle("Panel 1").SetSubTitle("Supporting tool or output panel").SetContentInset(DPI(8)).SetMediaGap(DPI(10)).SetMediaReserve(DPI(24)).SetMediaMin(DPI(16)).SetMediaAutoFit(false).SetMediaSide(UiAlign::LEFT).SetMediaAlign(UiAlign::CENTER, UiAlign::CENTER);
		Panel_2.SetTitle("Panel 2").SetSubTitle("Supporting tool or output panel").SetContentInset(DPI(8)).SetMediaGap(DPI(10)).SetMediaReserve(DPI(24)).SetMediaMin(DPI(16)).SetMediaAutoFit(false).SetMediaSide(UiAlign::LEFT).SetMediaAlign(UiAlign::CENTER, UiAlign::CENTER);
		Panel_3.SetTitle("Panel 3").SetSubTitle("Supporting tool or output panel").SetContentInset(DPI(8)).SetMediaGap(DPI(10)).SetMediaReserve(DPI(24)).SetMediaMin(DPI(16)).SetMediaAutoFit(false).SetMediaSide(UiAlign::LEFT).SetMediaAlign(UiAlign::CENTER, UiAlign::CENTER);
		lowerlayout.SetDirection(UiDirection::V).SetGap(DPI(8), DPI(8)).SetInset(DPI(6)).SetWrap(UiBoxWrap::None);
		status_label.SetText("Ready. Preset covers split buttons, dropdown, tool buttons, scroll panels, spacers, and role surfaces.");
		status_label.SetAlign(UiAlign::LEFT, UiAlign::CENTER);
		status_label.SetIconSide(UiAlign::LEFT);
		status_label.SetContentGap(DPI(6));
		status_label.SetIconScaleToContent(false);
		// Layout tree.
		Add(main_box);
		main_box.HSizePosZ(0, 0);
		main_box.VSizePosZ(0, 0);
		main_box.Add(lowerlayout).Fit().MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
		lowerlayout.Add(status_label).Fit().MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Start);
		main_box.Add(center_box).Expand(1).MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
		center_box.Add(rightlayout).Fit().MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
		rightlayout.Add(scrollpanel_02).Expand(1).MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
		scrollpanel_02.Content().Add(right_scroll_content.SizePos());
		right_scroll_content.Add(Panel_3).Fixed(DPI(68)).MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
		right_scroll_content.Add(Panel_2).Fixed(DPI(68)).MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
		right_scroll_content.Add(Panel_1).Fixed(DPI(68)).MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
		right_scroll_content.Add(Inspector).Fixed(DPI(68)).MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
		rightlayout.Add(right_tools_panel).Fit().MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Start);
		right_tools_panel.Add(right_tools.SizePos());
		{
			auto spacer = right_tools.AddSpacer(1);
			spacer.Fit().MinMain(DPI(10));
			spacer.MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
		}
		right_tools.Add(tool_09).Fit().MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Start);
		right_tools.Add(tool_08).Fit().MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Start);
		right_tools.Add(tool_07).Fit().MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Start);
		right_tools.Add(tool_06).Fit().MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Start);
		right_tools.Add(close_right).Fit().MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Start);
		center_box.Add(previewlayout).Expand(1).MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
		previewlayout.Add(preview_surface).Expand(1).MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
		preview_surface.Add(preview_stack.SizePos());
		preview_stack.Add(notes).Fit().MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
		preview_stack.Add(Canvas).Expand(1).MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
		previewlayout.Add(Preview).Fixed(DPI(72)).MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
		center_box.Add(leftlayout).Fit().MinMain(DPI(56)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
		leftlayout.Add(scrollpanel).Expand(1).MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
		scrollpanel.Content().Add(left_scroll_content.SizePos());
		left_scroll_content.Add(Library_3).Fixed(DPI(68)).MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
		left_scroll_content.Add(Library_2).Fixed(DPI(68)).MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
		left_scroll_content.Add(Library_1).Fixed(DPI(68)).MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
		left_scroll_content.Add(Toolbox).Fixed(DPI(68)).MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
		leftlayout.Add(left_tools_panel).Fit().MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Start);
		left_tools_panel.Add(left_tools.SizePos());
		left_tools.Add(close_left).Fit().MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Start);
		{
			auto spacer = left_tools.AddSpacer(1);
			spacer.Fit().MinMain(DPI(10));
			spacer.MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
		}
		left_tools.Add(tool_05).Fit().MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Start);
		left_tools.Add(tool_04).Fit().MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Start);
		left_tools.Add(tool_03).Fit().MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Start);
		left_tools.Add(tool_02).Fit().MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Start);
		left_tools.Add(tool).Fit().MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Start);
		main_box.Add(top_box).Fit().MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
		top_box.Add(exit_button).Fit().MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Start);
		top_box.Add(help_button).Fit().MinMain(DPI(65)).MinCross(DPI(24)).AlignSelf(UiBoxLayout::Align::Start);
		top_box.Add(dark_toggle).Fit().MinMain(DPI(65)).MinCross(DPI(24)).AlignSelf(UiBoxLayout::Align::Start);
		top_box.Add(theme_dropdown).Fit().MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Start);
		{
			auto spacer = top_box.AddSpacer(1);
			spacer.Expand(1).MinMain(DPI(10));
			spacer.MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
		}
		top_box.Add(version_badge).Fit().MinMain(DPI(76)).MinMaxCross(DPI(28), DPI(28)).AlignSelf(UiBoxLayout::Align::Start);
		top_box.Add(load_button).Fit().MinMain(DPI(10)).MinCross(DPI(24)).AlignSelf(UiBoxLayout::Align::Start);
		top_box.Add(save_button).Fit().MinMain(DPI(10)).MinCross(DPI(24)).AlignSelf(UiBoxLayout::Align::Start);
		{
			auto spacer = top_box.AddSpacer(1);
			spacer.Fit().MinMain(DPI(10));
			spacer.MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Stretch);
		}
		top_box.Add(titlecard).Fit().MinMain(DPI(10)).MinCross(DPI(10)).AlignSelf(UiBoxLayout::Align::Start);
		// Post-add setup.
	}
	UiBoxLayout main_box;
	UiBoxLayout top_box;
	UiTitleCard titlecard;
	UiSplitButton save_button;
	UiSplitButton load_button;
	UiLabel version_badge;
	UiDropdown theme_dropdown;
	UiToolButton dark_toggle;
	UiToolButton help_button;
	UiButton exit_button;
	UiBoxLayout center_box;
	UiBoxLayout leftlayout;
	UiPanel left_tools_panel;
	UiBoxLayout left_tools;
	UiToolButton tool;
	UiToolButton tool_02;
	UiToolButton tool_03;
	UiToolButton tool_04;
	UiToolButton tool_05;
	UiToolButton close_left;
	UiScrollPanel scrollpanel;
	UiBoxLayout left_scroll_content;
	UiTitleCard Toolbox;
	UiTitleCard Library_1;
	UiTitleCard Library_2;
	UiTitleCard Library_3;
	UiBoxLayout previewlayout;
	UiTitleCard Preview;
	UiPanel preview_surface;
	UiBoxLayout preview_stack;
	UiTitleCard Canvas;
	UiLabel notes;
	UiBoxLayout rightlayout;
	UiPanel right_tools_panel;
	UiBoxLayout right_tools;
	UiToolButton close_right;
	UiToolButton tool_06;
	UiToolButton tool_07;
	UiToolButton tool_08;
	UiToolButton tool_09;
	UiScrollPanel scrollpanel_02;
	UiBoxLayout right_scroll_content;
	UiTitleCard Inspector;
	UiTitleCard Panel_1;
	UiTitleCard Panel_2;
	UiTitleCard Panel_3;
	UiBoxLayout lowerlayout;
	UiLabel status_label;
};
GUI_APP_MAIN
{
	DesignerExportSmokeWindow().Run();
}
