// Generated by U++ Ui Designer.
// Designer version: v1.0.0-rc4
// Appearance mode: ThemeFirst
// Source design: design_color_picker_color.json
// Package: design_color_picker_color
// UMK path: E:\upp-18468\umk.exe
// Exported package: E:\apps\github\upp_Ui\designs\DesignerExportColorPicker
// Build method: CLANGx64
// Output executable: [PATH_TO_OUTPUT_EXE]
// Regenerate from design.json when the Designer model changes.
// This file is theme-first generated output.
// Explicit Designer appearance overrides are marked in code.

#include <CtrlLib/CtrlLib.h>
#include <Ui/Ui.h>

using namespace Upp;

// -----------------------------------------------------------------------------
// Theme candidates
// -----------------------------------------------------------------------------
// Designer appearance export omitted in theme-first mode.
// Instance-specific text, layout, data, and event wiring remain outside this section.

class design_color_picker_colorWindow : public TopWindow {
public:
	typedef design_color_picker_colorWindow CLASSNAME;

	design_color_picker_colorWindow()
	{
		InitWindow();
		InitThemeContext();
		BuildControls();
		ApplyAppearanceOverrides();
		BuildLayout();
		PostBuild();
	}

private:
	void InitWindow()
	{
		Title("Generated Designer Layout");
		Sizeable().Zoomable();
		SetRect(0, 0, DPI(706), DPI(484));
	}

	void InitThemeContext()
	{
		// Move this method to GeneratedDesignerTheme.cpp if splitting the generated app.
		// Theme context / preset setup.
	}

	void BuildControls()
	{
		// Control text, icons, values, ranges, roles, and basic behaviour.
		mainColumn.SetMinSize(Size(DPI(387), DPI(222)));
		mainColumn.SetDirection(UiDirection::V).SetGap(DPI(0), DPI(0)).SetInset(DPI(0)).SetWrap(UiBoxWrap::None);
		contentGrid.SetGridSize(2, 1).SetMinCellSize(Size(DPI(10), DPI(10))).SetGap(DPI(4)).SetInset(DPI(4));
		boxlayout.SetDirection(UiDirection::H).SetGap(DPI(4), DPI(0)).SetInset(DPI(4)).SetWrap(UiBoxWrap::None);
		colour_btn.SetCustomStyle(UiTheme::ResolveButton(UiRole::Accent));
		colour_btn.SetMinSize(Size(DPI(60), DPI(0)));
		colour_btn.SetText("Color").SetContentInset(DPI(6)).SetContentGap(DPI(4));
		colour_btn.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		colour_btn.SetIconSide(UiAlign::LEFT);
		pellet_btn.SetCustomStyle(UiTheme::ResolveButton(UiRole::Accent));
		pellet_btn.SetMinSize(Size(DPI(60), DPI(0)));
		pellet_btn.SetText("Paletts").SetContentInset(DPI(6)).SetContentGap(DPI(4));
		pellet_btn.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		pellet_btn.SetIconSide(UiAlign::LEFT);
		curves_btn.SetCustomStyle(UiTheme::ResolveButton(UiRole::Accent));
		curves_btn.SetMinSize(Size(DPI(60), DPI(0)));
		curves_btn.SetText("Curves").SetContentInset(DPI(6)).SetContentGap(DPI(4));
		curves_btn.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		curves_btn.SetIconSide(UiAlign::LEFT);
		generator_btn.SetCustomStyle(UiTheme::ResolveButton(UiRole::Accent));
		generator_btn.SetMinSize(Size(DPI(60), DPI(0)));
		generator_btn.SetText("Generator").SetContentInset(DPI(6)).SetContentGap(DPI(4));
		generator_btn.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		generator_btn.SetIconSide(UiAlign::LEFT);
		colour_slots_layout.SetGridSize(4, 2).SetMinCellSize(Size(DPI(10), DPI(10))).SetGap(DPI(4)).SetInset(DPI(0));
		colour_slot_3_previous.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		colour_slot_3_previous.SetMinSize(Size(DPI(0), DPI(8)));
		colour_slot_3_previous.SetText("").SetContentInset(DPI(0)).SetContentGap(DPI(0));
		colour_slot_3_previous.SetAlign(UiAlign::LEFT, UiAlign::CENTER);
		colour_slot_3_previous.SetIconSide(UiAlign::LEFT);
		colour_slot_1_primary.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		colour_slot_1_primary.SetText("").SetContentInset(DPI(0)).SetContentGap(DPI(0));
		colour_slot_1_primary.SetAlign(UiAlign::LEFT, UiAlign::CENTER);
		colour_slot_1_primary.SetIconSide(UiAlign::LEFT);
		colour_slot_1_primary.Tip("s");
		colour_slot_2_primary.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		colour_slot_2_primary.SetText("").SetContentInset(DPI(0)).SetContentGap(DPI(0));
		colour_slot_2_primary.SetAlign(UiAlign::LEFT, UiAlign::CENTER);
		colour_slot_2_primary.SetIconSide(UiAlign::LEFT);
		colour_slot_4_primary.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		colour_slot_4_primary.SetText("").SetContentInset(DPI(0)).SetContentGap(DPI(0));
		colour_slot_4_primary.SetAlign(UiAlign::LEFT, UiAlign::CENTER);
		colour_slot_4_primary.SetIconSide(UiAlign::LEFT);
		color_slot_1_previous.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		color_slot_1_previous.SetMinSize(Size(DPI(8), DPI(6)));
		color_slot_1_previous.SetText("").SetContentInset(DPI(0)).SetContentGap(DPI(0));
		color_slot_1_previous.SetAlign(UiAlign::LEFT, UiAlign::CENTER);
		color_slot_1_previous.SetIconSide(UiAlign::LEFT);
		color_slot_2_previous.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		color_slot_2_previous.SetMinSize(Size(DPI(0), DPI(8)));
		color_slot_2_previous.SetText("").SetContentInset(DPI(0)).SetContentGap(DPI(0));
		color_slot_2_previous.SetAlign(UiAlign::LEFT, UiAlign::CENTER);
		color_slot_2_previous.SetIconSide(UiAlign::LEFT);
		colour_slot_4_previous.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		colour_slot_4_previous.SetMinSize(Size(DPI(0), DPI(8)));
		colour_slot_4_previous.SetText("").SetContentInset(DPI(0)).SetContentGap(DPI(0));
		colour_slot_4_previous.SetAlign(UiAlign::LEFT, UiAlign::CENTER);
		colour_slot_4_previous.SetIconSide(UiAlign::LEFT);
		colour_slot_3_primary.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		colour_slot_3_primary.SetText("").SetContentInset(DPI(0)).SetContentGap(DPI(0));
		colour_slot_3_primary.SetAlign(UiAlign::LEFT, UiAlign::CENTER);
		colour_slot_3_primary.SetIconSide(UiAlign::LEFT);
		colour_slot_current.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		colour_slot_current.SetText("").SetContentInset(DPI(0)).SetContentGap(DPI(0));
		colour_slot_current.SetAlign(UiAlign::LEFT, UiAlign::CENTER);
		colour_slot_current.SetIconSide(UiAlign::LEFT);
		colour_slot_current.Tip("Current color");
		boxlayout_03.SetDirection(UiDirection::H).SetGap(DPI(4), DPI(0)).SetInset(DPI(0)).SetWrap(UiBoxWrap::None);
		gridlayout_02.SetGridSize(1, 2).SetMinCellSize(Size(DPI(10), DPI(10))).SetGap(DPI(4)).SetInset(DPI(0));
		spectrum_drop_down.UseInternalModel().Clear().Add("First", "First");
		spectrum_drop_down.Select(0);
		spectrum_drop_down.SetIndicatorSide(UiAlign::RIGHT);
		spectrum_drop_down.SetIndicatorSize(DPI(14));
		color_spectrum_panel.SetCustomStyle(UiTheme::ResolvePanel(UiRole::Accent));
		color_spectrum_panel.SetSizeMin(DPI(309), DPI(200));
		color_spectrum_panel.SetInset(DPI(0));
		color_spectrum_panel.Tip("Color");
		color_right_grid_layout.SetGridSize(1, 4).SetMinCellSize(Size(DPI(10), DPI(10))).SetGap(DPI(4)).SetInset(DPI(0));
		ok_btn.SetCustomStyle(UiTheme::ResolveButton(UiRole::Accent));
		ok_btn.SetText("OK").SetContentInset(DPI(6)).SetContentGap(DPI(4));
		ok_btn.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		ok_btn.SetIconSide(UiAlign::LEFT);
		cancel_btn.SetCustomStyle(UiTheme::ResolveButton(UiRole::Alert));
		cancel_btn.SetText("Cancel").SetContentInset(DPI(6)).SetContentGap(DPI(4));
		cancel_btn.SetAlign(UiAlign::CENTER, UiAlign::CENTER);
		cancel_btn.SetIconSide(UiAlign::LEFT);
		slider_selector_layout.SetGridSize(3, 1).SetMinCellSize(Size(DPI(10), DPI(10))).SetGap(DPI(2)).SetInset(DPI(0)).SetDebugColor(Color(220, 38, 38)).SetDebug(true);
		information_detail_label.SetText("Information/Detail");
		information_detail_label.SetAlign(UiAlign::LEFT, UiAlign::CENTER);
		information_detail_label.SetIconSide(UiAlign::LEFT);
		information_detail_label.SetContentGap(DPI(6));
		information_detail_label.SetIconScaleToContent(false);
		gridlayout.SetGridSize(3, 4).SetMinCellSize(Size(DPI(10), DPI(10))).SetGap(DPI(0)).SetInset(DPI(0));
		r_slider.SetRange(0, 100).SetValue(50);
		label.SetCustomStyle(UiTheme::ResolveLabel(UiRole::Subtle));
		label.SetMinSize(Size(DPI(35), DPI(0)));
		label.SetText("R");
		label.SetAlign(UiAlign::LEFT, UiAlign::CENTER);
		label.SetIconSide(UiAlign::LEFT);
		label.SetContentGap(DPI(6));
		label.SetIconScaleToContent(false);
		label_02.SetMinSize(Size(DPI(35), DPI(0)));
		label_02.SetText("G");
		label_02.SetAlign(UiAlign::LEFT, UiAlign::CENTER);
		label_02.SetIconSide(UiAlign::LEFT);
		label_02.SetContentGap(DPI(6));
		label_02.SetIconScaleToContent(false);
		label_03.SetCustomStyle(UiTheme::ResolveLabel(UiRole::Subtle));
		label_03.SetMinSize(Size(DPI(35), DPI(0)));
		label_03.SetText("B");
		label_03.SetAlign(UiAlign::LEFT, UiAlign::CENTER);
		label_03.SetIconSide(UiAlign::LEFT);
		label_03.SetContentGap(DPI(6));
		label_03.SetIconScaleToContent(false);
		label_04.SetCustomStyle(UiTheme::ResolveLabel(UiRole::Accent));
		label_04.SetMinSize(Size(DPI(35), DPI(0)));
		label_04.SetText("A");
		label_04.SetAlign(UiAlign::LEFT, UiAlign::CENTER);
		label_04.SetIconSide(UiAlign::LEFT);
		label_04.SetContentGap(DPI(6));
		label_04.SetIconScaleToContent(false);
		r_edit.SetCustomStyle(UiTheme::ResolveEdit(UiRole::Subtle));
		r_edit.SetMinSize(Size(DPI(58), DPI(21)));
		r_edit.MinMax(0, 10).Step(0.1).Precision(6).ShowSpin(false);
		r_edit.SetValue(0.2102);
		r_edit_02.SetCustomStyle(UiTheme::ResolveEdit(UiRole::Subtle));
		r_edit_02.SetMinSize(Size(DPI(58), DPI(21)));
		r_edit_02.MinMax(0, 10).Step(0.1).Precision(6).ShowSpin(false);
		r_edit_02.SetValue(0.2102);
		r_edit_03.SetCustomStyle(UiTheme::ResolveEdit(UiRole::Subtle));
		r_edit_03.SetMinSize(Size(DPI(58), DPI(21)));
		r_edit_03.MinMax(0, 10).Step(0.1).Precision(6).ShowSpin(false);
		r_edit_03.SetValue(0.2102);
		r_edit_04.SetCustomStyle(UiTheme::ResolveEdit(UiRole::Subtle));
		r_edit_04.SetMinSize(Size(DPI(58), DPI(21)));
		r_edit_04.MinMax(0, 10).Step(0.1).Precision(6).ShowSpin(false);
		r_edit_04.SetValue(0.2102);
		r_slider_02.SetRange(0, 100).SetValue(50);
		r_slider_03.SetRange(0, 100).SetValue(50);
		r_slider_04.SetRange(0, 100).SetValue(50);
		gridlayout_03_02.SetMinSize(Size(DPI(300), DPI(160)));
		gridlayout_03_02.SetGridSize(2, 3).SetMinCellSize(Size(DPI(10), DPI(10))).SetGap(DPI(2)).SetInset(DPI(0));
		grouppanel_05.SetMinSize(Size(DPI(0), DPI(43)));
		grouppanel_05.SetTitle("HSV").SetSubTitle("").SetSideTitle("").SetHeaderMode(UiGroupPanel::Center).SetHeaderPlacement(UiAlign::TOP).SetLine(false).SetHeaderBand(false).SetLineThickness(DPI(1)).SetInset(Rect(DPI(0), DPI(0), DPI(0), DPI(0))).SetHeaderInset(Rect(DPI(11), DPI(11), DPI(11), DPI(11)));
			grouppanel_02_02.SetMinSize(Size(DPI(0), DPI(44)));
		grouppanel_02_02.SetTitle("RGB (HEX)").SetSubTitle("").SetSideTitle("").SetHeaderMode(UiGroupPanel::Center).SetHeaderPlacement(UiAlign::TOP).SetLine(false).SetHeaderBand(false).SetLineThickness(DPI(1)).SetInset(Rect(DPI(0), DPI(0), DPI(0), DPI(0))).SetHeaderInset(Rect(DPI(11), DPI(11), DPI(11), DPI(11)));
				grouppanel_03_02.SetMinSize(Size(DPI(0), DPI(44)));
		grouppanel_03_02.SetTitle("HLS").SetSubTitle("").SetSideTitle("").SetHeaderMode(UiGroupPanel::Center).SetHeaderPlacement(UiAlign::TOP).SetLine(false).SetHeaderBand(false).SetLineThickness(DPI(1)).SetInset(Rect(DPI(0), DPI(0), DPI(0), DPI(0))).SetHeaderInset(Rect(DPI(11), DPI(11), DPI(11), DPI(11)))	;	grouppanel_04_02.SetMinSize(Size(DPI(0), DPI(44)));
		grouppanel_04_02.SetTitle("RGB (Float)").SetSubTitle("").SetSideTitle("").SetHeaderMode(UiGroupPanel::Center).SetHeaderPlacement(UiAlign::TOP).SetLine(false).SetHeaderBand(false).SetLineThickness(DPI(1)).SetInset(Rect(DPI(0), DPI(0), DPI(0), DPI(0))).SetHeaderInset(Rect(DPI(11), DPI(11), DPI(11), DPI(11)))	;	gridlayout_03.SetGridSize(3, 2).SetMinCellSize(Size(DPI(10), DPI(10))).SetGap(DPI(0)).SetInset(DPI(0));
		label_05.SetCustomStyle(UiTheme::ResolveLabel(UiRole::Subtle));
		label_05.SetMinSize(Size(DPI(35), DPI(0)));
		label_05.SetText("Hue");
		label_05.SetAlign(UiAlign::LEFT, UiAlign::CENTER);
		label_05.SetIconSide(UiAlign::LEFT);
		label_05.SetContentGap(DPI(6));
		label_05.SetIconScaleToContent(false);
		r_slider_05.SetRange(0, 100).SetValue(50);
		r_edit_05.SetCustomStyle(UiTheme::ResolveEdit(UiRole::Subtle));
		r_edit_05.SetMinSize(Size(DPI(58), DPI(21)));
		r_edit_05.MinMax(0, 10).Step(0.1).Precision(6).ShowSpin(false);
		r_edit_05.SetValue(0.2102);
		label_02_02.SetMinSize(Size(DPI(35), DPI(0)));
		label_02_02.SetText("Gain");
		label_02_02.SetAlign(UiAlign::LEFT, UiAlign::CENTER);
		label_02_02.SetIconSide(UiAlign::LEFT);
		label_02_02.SetContentGap(DPI(6));
		label_02_02.SetIconScaleToContent(false);
		r_slider_02_02.SetRange(0, 100).SetValue(50);
		r_edit_02_02.SetCustomStyle(UiTheme::ResolveEdit(UiRole::Subtle));
		r_edit_02_02.SetMinSize(Size(DPI(58), DPI(21)));
		r_edit_02_02.MinMax(0, 10).Step(0.1).Precision(6).ShowSpin(false);
		r_edit_02_02.SetValue(0.2102);
		grouppanel_02_02_03.SetMinSize(Size(DPI(0), DPI(44)));
		grouppanel_02_02_03.SetTitle("RGB (8BIT)").SetSubTitle("").SetSideTitle("").SetHeaderMode(UiGroupPanel::Center).SetHeaderPlacement(UiAlign::TOP).SetLine(false).SetHeaderBand(false).SetLineThickness(DPI(1)).SetInset(Rect(DPI(0), DPI(0), DPI(0), DPI(0))).SetHeaderInset(Rect(DPI(11), DPI(11), DPI(11), DPI(11)));
		grouppanel_02_02_02.SetMinSize(Size(DPI(0), DPI(44)));
		grouppanel_02_02_02.SetTitle("CMYK").SetSubTitle("").SetSideTitle("").SetHeaderMode(UiGroupPanel::Center).SetHeaderPlacement(UiAlign::TOP).SetLine(false).SetHeaderBand(false).SetLineThickness(DPI(1)).SetInset(Rect(DPI(0), DPI(0), DPI(0), DPI(0))).SetHeaderInset(Rect(DPI(11), DPI(11), DPI(11), DPI(11)));
		boxlayout_02.SetDirection(UiDirection::H).SetGap(DPI(0), DPI(0)).SetInset(DPI(0)).SetWrap(UiBoxWrap::None);
		lineedit.SetCustomStyle(UiTheme::ResolveEdit(UiRole::Subtle));
		lineedit.SetTextUtf8("50°, 70%, 66%");
		lineedit.SetPlaceholder("50°, 70%, 66%");
		toolbutton.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		toolbutton.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		toolbutton.SetAlign(UiAlign::RIGHT, UiAlign::CENTER);
		toolbutton.SetIconSide(UiAlign::LEFT);
		toolbutton.SetIcon(ICON_CONTENT_CONTENT_COPY_48()).SetIconSize(DPI(15), DPI(15));
		boxlayout_02_02.SetDirection(UiDirection::H).SetGap(DPI(0), DPI(0)).SetInset(DPI(0)).SetWrap(UiBoxWrap::None);
		lineedit_02.SetCustomStyle(UiTheme::ResolveEdit(UiRole::Subtle));
		lineedit_02.SetTextUtf8("#a89432");
		lineedit_02.SetPlaceholder("#a89432");
		toolbutton_02.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		toolbutton_02.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		toolbutton_02.SetAlign(UiAlign::RIGHT, UiAlign::CENTER);
		toolbutton_02.SetIconSide(UiAlign::LEFT);
		toolbutton_02.SetIcon(ICON_CONTENT_CONTENT_COPY_48()).SetIconSize(DPI(15), DPI(15));
		boxlayout_02_03.SetDirection(UiDirection::H).SetGap(DPI(0), DPI(0)).SetInset(DPI(0)).SetWrap(UiBoxWrap::None);
		lineedit_03.SetCustomStyle(UiTheme::ResolveEdit(UiRole::Subtle));
		lineedit_03.SetTextUtf8("0.6392, 0.5961, 0.1882, 1.0000");
		lineedit_03.SetPlaceholder("0.6392, 0.5961, 0.1882, 1.0000");
		toolbutton_03.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		toolbutton_03.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		toolbutton_03.SetAlign(UiAlign::RIGHT, UiAlign::CENTER);
		toolbutton_03.SetIconSide(UiAlign::LEFT);
		toolbutton_03.SetIcon(ICON_CONTENT_CONTENT_COPY_48()).SetIconSize(DPI(15), DPI(15));
		boxlayout_02_04.SetDirection(UiDirection::H).SetGap(DPI(0), DPI(0)).SetInset(DPI(0)).SetWrap(UiBoxWrap::None);
		lineedit_04.SetCustomStyle(UiTheme::ResolveEdit(UiRole::Subtle));
		lineedit_04.SetTextUtf8("50°, 54%, 43%");
		lineedit_04.SetPlaceholder("50°, 54%, 43%");
		toolbutton_04.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		toolbutton_04.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		toolbutton_04.SetAlign(UiAlign::RIGHT, UiAlign::CENTER);
		toolbutton_04.SetIconSide(UiAlign::LEFT);
		toolbutton_04.SetIcon(ICON_CONTENT_CONTENT_COPY_48()).SetIconSize(DPI(15), DPI(15));
		boxlayout_02_05.SetDirection(UiDirection::H).SetGap(DPI(0), DPI(0)).SetInset(DPI(0)).SetWrap(UiBoxWrap::None);
		lineedit_05.SetCustomStyle(UiTheme::ResolveEdit(UiRole::Subtle));
		lineedit_05.SetTextUtf8("0%, 12%, 70%, 34%");
		lineedit_05.SetPlaceholder("0%, 12%, 70%, 34%");
		toolbutton_05.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		toolbutton_05.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		toolbutton_05.SetAlign(UiAlign::RIGHT, UiAlign::CENTER);
		toolbutton_05.SetIconSide(UiAlign::LEFT);
		toolbutton_05.SetIcon(ICON_CONTENT_CONTENT_COPY_48()).SetIconSize(DPI(15), DPI(15));
		boxlayout_02_06.SetDirection(UiDirection::H).SetGap(DPI(0), DPI(0)).SetInset(DPI(0)).SetWrap(UiBoxWrap::None);
		lineedit_06.SetCustomStyle(UiTheme::ResolveEdit(UiRole::Subtle));
		lineedit_06.SetTextUtf8("168, 148, 50, 1");
		lineedit_06.SetPlaceholder("168, 148, 50, 1");
		toolbutton_06.SetCustomStyle(UiTheme::ResolveToolButton(UiRole::Subtle));
		toolbutton_06.SetText("").SetContentInset(DPI(4)).SetContentGap(DPI(4));
		toolbutton_06.SetAlign(UiAlign::RIGHT, UiAlign::CENTER);
		toolbutton_06.SetIconSide(UiAlign::LEFT);
		toolbutton_06.SetIcon(ICON_CONTENT_CONTENT_COPY_48()).SetIconSize(DPI(15), DPI(15));
		label_06.SetCustomStyle(UiTheme::ResolveLabel(UiRole::Subtle));
		label_06.SetText("Alpha");
		label_06.SetAlign(UiAlign::RIGHT, UiAlign::CENTER);
		label_06.SetIconSide(UiAlign::LEFT);
		label_06.SetContentGap(DPI(6));
		label_06.SetIconScaleToContent(false);
		footer_layout.SetDirection(UiDirection::H).SetGap(DPI(8), DPI(8)).SetInset(DPI(13)).SetWrap(UiBoxWrap::None);
		toggle_02_02.SetCustomStyle(UiTheme::ResolveToggle(UiRole::Accent));
		toggle_02_02.SetOn(true);
		dropdown.UseInternalModel().Clear().Add("First", "First");
		dropdown.Select(0);
		dropdown.SetIndicatorSide(UiAlign::RIGHT);
		dropdown.SetIndicatorSize(DPI(14));
	}

	void ApplyAppearanceOverrides()
	{
		// Designer appearance export omitted; theme-first output only.
	}

	void BuildLayout()
	{
		// Parent-child layout tree only.
		Add(mainColumn);
		mainColumn.Add(boxlayout).Fit().MinCross(DPI(0)).AlignSelf(UiBoxLayout::Align::Stretch);
		boxlayout.Add(gridlayout_02).Expand(1).MinCross(DPI(0)).AlignSelf(UiBoxLayout::Align::Stretch);
		boxlayout_03.Add(colour_btn).Expand(1).MinCross(DPI(0));
		boxlayout_03.Add(pellet_btn).Expand(1).MinCross(DPI(0));
		boxlayout_03.Add(curves_btn).Expand(1).MinCross(DPI(0));
		boxlayout_03.Add(generator_btn).Expand(1).MinCross(DPI(0));
		{
			auto spacer = boxlayout.AddSpacer(1);
			spacer.Expand(1).MinMain(DPI(2));
			spacer.MinCross(DPI(0)).AlignSelf(UiBoxLayout::Align::Stretch);
			spacer.LineEnabled(true).LineOrientation(UiSpacerLineOrientation::Vertical).LineAlign(UiCrossAlign::Center).LineThickness(DPI(2)).LineDash(SOLID).LineInset(DPI(0)).LineColorEnabled(true).LineColor(Color(199, 199, 199));
		}
		boxlayout.Add(colour_slot_current).Fixed(DPI(30)).MinCross(DPI(0)).AlignSelf(UiBoxLayout::Align::Stretch);
		boxlayout.Add(colour_slots_layout).Fit().MinCross(DPI(0)).AlignSelf(UiBoxLayout::Align::Stretch);
		mainColumn.Add(contentGrid).Expand(1).MinCross(DPI(0)).AlignSelf(UiBoxLayout::Align::Stretch);
		boxlayout_02.Add(lineedit).Expand(1).MinCross(DPI(0));
		boxlayout_02.Add(toolbutton).Fit().MinCross(DPI(0));
		boxlayout_02_02.Add(lineedit_02).Expand(1).MinCross(DPI(0));
		boxlayout_02_02.Add(toolbutton_02).Fit().MinCross(DPI(0));
		boxlayout_02_04.Add(lineedit_04).Expand(1).MinCross(DPI(0));
		boxlayout_02_04.Add(toolbutton_04).Fit().MinCross(DPI(0));
		boxlayout_02_03.Add(lineedit_03).Expand(1).MinCross(DPI(0));
		boxlayout_02_03.Add(toolbutton_03).Fit().MinCross(DPI(0));
		boxlayout_02_05.Add(lineedit_05).Expand(1).MinCross(DPI(0));
		boxlayout_02_05.Add(toolbutton_05).Fit().MinCross(DPI(0));
		boxlayout_02_06.Add(lineedit_06).Expand(1).MinCross(DPI(0));
		boxlayout_02_06.Add(toolbutton_06).Fit().MinCross(DPI(0));
		mainColumn.Add(footer_layout).Fit().MinCross(DPI(0)).AlignSelf(UiBoxLayout::Align::Stretch);
		footer_layout.Add(information_detail_label).Expand(1).MinCross(DPI(0));
		footer_layout.Add(ok_btn).Expand(1).MinCross(DPI(0));
		footer_layout.Add(cancel_btn).Expand(1).MinCross(DPI(0));
	}

	void PostBuild()
	{
		// Active tabs/pages and late setup.
	}

	UiBoxLayout mainColumn;
	UiGridLayout contentGrid;
	UiBoxLayout boxlayout;
	UiButton colour_btn;
	UiButton pellet_btn;
	UiButton curves_btn;
	UiButton generator_btn;
	UiGridLayout colour_slots_layout;
	UiToolButton colour_slot_3_previous;
	UiToolButton colour_slot_1_primary;
	UiToolButton colour_slot_2_primary;
	UiToolButton colour_slot_4_primary;
	UiToolButton color_slot_1_previous;
	UiToolButton color_slot_2_previous;
	UiToolButton colour_slot_4_previous;
	UiToolButton colour_slot_3_primary;
	UiToolButton colour_slot_current;
	UiBoxLayout boxlayout_03;
	UiGridLayout gridlayout_02;
	UiDropdown spectrum_drop_down;
	UiPanel color_spectrum_panel;
	UiGridLayout color_right_grid_layout;
	UiButton ok_btn;
	UiButton cancel_btn;
	UiGridLayout slider_selector_layout;
	UiLabel information_detail_label;
	UiGridLayout gridlayout;
	UiSlider r_slider;
	UiLabel label;
	UiLabel label_02;
	UiLabel label_03;
	UiLabel label_04;
	UiFloatEdit r_edit;
	UiFloatEdit r_edit_02;
	UiFloatEdit r_edit_03;
	UiFloatEdit r_edit_04;
	UiSlider r_slider_02;
	UiSlider r_slider_03;
	UiSlider r_slider_04;
	UiGridLayout gridlayout_03_02;
	UiGroupPanel grouppanel_05;
	UiGroupPanel grouppanel_02_02;
	UiGroupPanel grouppanel_03_02;
	UiGroupPanel grouppanel_04_02;
	UiGridLayout gridlayout_03;
	UiLabel label_05;
	UiSlider r_slider_05;
	UiFloatEdit r_edit_05;
	UiLabel label_02_02;
	UiSlider r_slider_02_02;
	UiFloatEdit r_edit_02_02;
	UiGroupPanel grouppanel_02_02_03;
	UiGroupPanel grouppanel_02_02_02;
	UiBoxLayout boxlayout_02;
	UiDirectContentHost boxlayout_02_host;
	UiLineEdit lineedit;
	UiToolButton toolbutton;
	UiBoxLayout boxlayout_02_02;
	UiDirectContentHost boxlayout_02_02_host;
	UiLineEdit lineedit_02;
	UiToolButton toolbutton_02;
	UiBoxLayout boxlayout_02_03;
	UiDirectContentHost boxlayout_02_03_host;
	UiLineEdit lineedit_03;
	UiToolButton toolbutton_03;
	UiBoxLayout boxlayout_02_04;
	UiDirectContentHost boxlayout_02_04_host;
	UiLineEdit lineedit_04;
	UiToolButton toolbutton_04;
	UiBoxLayout boxlayout_02_05;
	UiDirectContentHost boxlayout_02_05_host;
	UiLineEdit lineedit_05;
	UiToolButton toolbutton_05;
	UiBoxLayout boxlayout_02_06;
	UiDirectContentHost boxlayout_02_06_host;
	UiLineEdit lineedit_06;
	UiToolButton toolbutton_06;
	UiLabel label_06;
	UiBoxLayout footer_layout;
	UiToggle toggle_02_02;
	UiDropdown dropdown;
};

GUI_APP_MAIN
{
	design_color_picker_colorWindow().Run();
}
