TITLE("UiItemRender")
TOPIC_TEXT(
"UiItemRender is the shared lightweight presentation layer for model-backed Ui views. "
"UiItemRenderData carries semantic display content such as title, description, image/icon, "
"metadata and enabled state. A UiItemRender is not a Ctrl and is not allocated once per "
"logical model record: high-scale views clone a configured renderer prototype only for "
"visible/overscan surfaces and recycle those instances as the viewport moves. "
"\n\n"
"The renderer owns presentation inside the rectangle assigned by its view. PrepareLayout() "
"is the public dirty-gated preparation entry point; it invokes the protected virtual Layout() "
"only when bound data, theme, rectangle, direction or renderer configuration requires new "
"geometry. Paint() and HitTest() consume that prepared geometry and must never perform layout. "
"GetContentSize() reports natural content size and GetMinSize() reports the smallest useful "
"presentation size; neither changes the view's authoritative allocated row/tile/cell geometry. "
"\n\n"
"UiItemRenderBasic is the standard text/icon/check/metadata renderer and UiItemRenderImage is "
"the standard image-first renderer. Both support horizontal and vertical presentation and use "
"the existing UiTheme, UiRole, StyledPalette, StyledMetrics, StyledSkin and UiIconRenderMode "
"style vocabulary. Use SetCustomStyle() on the renderer prototype for an authored renderer "
"appearance; otherwise runtime Ui theme changes are inherited. "
"\n\n"
"UiList defaults to a horizontal UiItemRenderBasic. UiGallery defaults to a vertical "
"UiItemRenderImage and falls back from UiModelItem.image to UiModelItem.icon when no image is "
"present. SetItemRender() replaces the renderer prototype without transferring model, selection, "
"scrolling, hierarchy or topology ownership away from the view. Future Tree/Table/Graph adoption "
"uses the same rule: one logical record may expose several render surfaces (for example a Tree "
"primary cell plus columns) without becoming several logical model records."
)
