#ifndef _Utilities_SymbolPicker_SmokeHeaderCompile_GeneratedRleHeader_h_
#define _Utilities_SymbolPicker_SmokeHeaderCompile_GeneratedRleHeader_h_

#include <CtrlLib/CtrlLib.h>
#include <Ui/UiDraw.h>

// Generated by SymbolPicker smoke fixture.
// Export format: UiMakeIcon RLE

static const unsigned char DATA_SMOKE_RLE_SAVE[] = {
	0x01, 0x80, 0x01, 0x00,
	0x01, 0x00, 0xFF, 0x00, 0x00, 0xFF
};

inline Upp::Image ICON_SMOKE_RLE_SAVE()
{
	return Upp::UiMakeIcon(DATA_SMOKE_RLE_SAVE);
}

#endif
