#ifndef _Utilities_SymbolPicker_SmokeHeaderCompile_GeneratedRleHeader_h_
#define _Utilities_SymbolPicker_SmokeHeaderCompile_GeneratedRleHeader_h_

#include <CtrlLib/CtrlLib.h>
#include <Ui/UiDraw.h>

// Generated by SymbolPicker.
// Project: SmokeHeaderCompile
// Export format: UiMakeIcon RLE
// RLE encoding: uint16 little-endian run length followed by premultiplied RGBA.
// Deterministic export; no timestamps.

static const unsigned char DATA_SMOKE_RLE_SAVE[] = {
	0x01, 0x80, 0x01, 0x00,
	0x01, 0x00, 0xFF, 0x00, 0x00, 0xFF
};

inline Upp::Image ICON_SMOKE_RLE_SAVE()
{
	return Upp::UiMakeIcon(DATA_SMOKE_RLE_SAVE);
}

#endif // _Utilities_SymbolPicker_SmokeHeaderCompile_GeneratedRleHeader_h_
