#ifndef _Utilities_SymbolPicker_SmokeHeaderCompile_GeneratedRawHeader_h_
#define _Utilities_SymbolPicker_SmokeHeaderCompile_GeneratedRawHeader_h_

#include <CtrlLib/CtrlLib.h>
#include <Ui/UiDraw.h>

// Generated by SymbolPicker.
// Project: SmokeHeaderCompile
// Export format: UiMakeIcon RAW
// RAW encoding: row-major premultiplied RGBA bytes.
// Deterministic export; no timestamps.

static const unsigned char DATA_SMOKE_RAW_SAVE[] = {
	0x01, 0x00, 0x01, 0x00,
	0xFF, 0x00, 0x00, 0xFF
};

inline Upp::Image ICON_SMOKE_RAW_SAVE()
{
	return Upp::UiMakeIcon(DATA_SMOKE_RAW_SAVE);
}

#endif // _Utilities_SymbolPicker_SmokeHeaderCompile_GeneratedRawHeader_h_
