// Generated by SymbolPicker.
// Project:
// SmokeHeaderCompileRle
// Export format: UiMakeIcon RLE
// RLE encoding: uint16 little-endian run length followed by premultiplied RGBA.
// Deterministic export; no timestamps.

#ifndef SMOKEHEADERCOMPILERLE_UPP_RLE_HEADER_H
#define SMOKEHEADERCOMPILERLE_UPP_RLE_HEADER_H

#include <CtrlLib/CtrlLib.h>
#include <Ui/UiDraw.h>

// Collection:
// Rle
// Category:
// Rle
// Symbol:
// ICON_SMOKE_RLE_COPY
// Icon:
// Copy
// Source:
// action/3d_rotation
// Style: outlined | Size: 24
static const unsigned char DATA_ICON_SMOKE_RLE_COPY[] = {
    0x18, 0x80, 0x18, 0x00, 0x40, 0x02, 0x00, 0x00, 0x00, 0x00
};

inline Upp::Image ICON_SMOKE_RLE_COPY()
{
    return Upp::UiMakeIcon(DATA_ICON_SMOKE_RLE_COPY);
}

#endif // SMOKEHEADERCOMPILERLE_UPP_RLE_HEADER_H
