#ifndef _SYMBOLPICKER_GENERATED_UIICONS_h_
#define _SYMBOLPICKER_GENERATED_UIICONS_h_

#include <CtrlCore/CtrlCore.h>
#include <Ui/UiDataModels.h>

namespace Upp {

#define IMAGECLASS UiIconsImg
#define IMAGEFILE <Ui/UiIcons.iml>
#include <Draw/iml_header.h>

// Define UIICONS_IML_IMPLEMENTATION in exactly one .cpp before including this header.
#ifdef UIICONS_IML_IMPLEMENTATION
#define IMAGECLASS UiIconsImg
#define IMAGEFILE <Ui/UiIcons.iml>
#include <Draw/iml_source.h>
#endif

inline Image ICON_NAVIGATION_OUTLINED_MORE_HORIZ_48() { return UiIconsImg::ICON_NAVIGATION_OUTLINED_MORE_HORIZ_48(); }
inline Image ICON_NAVIGATION_OUTLINED_MORE_VERT_48() { return UiIconsImg::ICON_NAVIGATION_OUTLINED_MORE_VERT_48(); }
inline Image ICON_NAVIGATION_OUTLINED_ARROW_RIGHT_48() { return UiIconsImg::ICON_NAVIGATION_OUTLINED_ARROW_RIGHT_48(); }
inline Image ICON_NAVIGATION_OUTLINED_ARROW_LEFT_48() { return UiIconsImg::ICON_NAVIGATION_OUTLINED_ARROW_LEFT_48(); }
inline Image ICON_NAVIGATION_OUTLINED_ARROW_DROP_UP_48() { return UiIconsImg::ICON_NAVIGATION_OUTLINED_ARROW_DROP_UP_48(); }
inline Image ICON_NAVIGATION_OUTLINED_ARROW_DROP_DOWN_48() { return UiIconsImg::ICON_NAVIGATION_OUTLINED_ARROW_DROP_DOWN_48(); }
inline Image ICON_NAVIGATION_CLOSE_SMALL_48() { return UiIconsImg::ICON_NAVIGATION_CLOSE_SMALL_48(); }
inline Image ICON_HARDWARE_OUTLINED_KEYBOARD_ARROW_RIGHT_48() { return UiIconsImg::ICON_HARDWARE_OUTLINED_KEYBOARD_ARROW_RIGHT_48(); }
inline Image ICON_CONTENT_OUTLINED_ADD_48() { return UiIconsImg::ICON_CONTENT_OUTLINED_ADD_48(); }
inline Image ICON_CONTENT_CONTENT_COPY_48() { return UiIconsImg::ICON_CONTENT_CONTENT_COPY_48(); }
inline Image ICON_ACTION_OUTLINED_VISIBILITY_48() { return UiIconsImg::ICON_ACTION_OUTLINED_VISIBILITY_48(); }
inline Image ICON_ACTION_OUTLINED_VISIBILITY_OFF_48() { return UiIconsImg::ICON_ACTION_OUTLINED_VISIBILITY_OFF_48(); }
inline Image ICON_ACTION_SEARCH_48() { return UiIconsImg::ICON_ACTION_SEARCH_48(); }
inline Image ICON_ACTION_DARK_MODE_48() { return UiIconsImg::ICON_ACTION_DARK_MODE_48(); }
inline Image ICON_ACTION_LIGHT_MODE_48() { return UiIconsImg::ICON_ACTION_LIGHT_MODE_48(); }
inline Image ICON_DESIGN_CHECK_SMALL_48() { return UiIconsImg::ICON_DESIGN_CHECK_SMALL_48(); }
inline Image ICON_DESIGN_DELETE_48() { return UiIconsImg::ICON_DESIGN_DELETE_48(); }
inline Image ICON_DESIGN_DRAG_INDICATOR_48() { return UiIconsImg::ICON_DESIGN_DRAG_INDICATOR_48(); }
inline Image ICON_DESIGN_FOLDER_48() { return UiIconsImg::ICON_DESIGN_FOLDER_48(); }
inline Image ICON_DESIGN_HOME_48() { return UiIconsImg::ICON_DESIGN_HOME_48(); }
inline Image ICON_DESIGN_IMAGE_48() { return UiIconsImg::ICON_DESIGN_IMAGE_48(); }
inline Image ICON_DESIGN_LOWERCASE_48() { return UiIconsImg::ICON_DESIGN_LOWERCASE_48(); }
inline Image ICON_DESIGN_SETTINGS_48() { return UiIconsImg::ICON_DESIGN_SETTINGS_48(); }
inline Image ICON_DESIGN_UPPERCASE_48() { return UiIconsImg::ICON_DESIGN_UPPERCASE_48(); }
inline Image ICON_DESIGN_ADJUST_48() { return UiIconsImg::ICON_DESIGN_ADJUST_48(); }
inline Image ICON_DESIGN_CIRCLE_48() { return UiIconsImg::ICON_DESIGN_CIRCLE_48(); }
inline Image ICON_DESIGN_ACCOUNT_TREE_48() { return UiIconsImg::ICON_DESIGN_ACCOUNT_TREE_48(); }
inline Image ICON_DESIGN_LABEL_48() { return UiIconsImg::ICON_DESIGN_LABEL_48(); }
inline Image ICON_DESIGN_TOGGLE_ON_48() { return UiIconsImg::ICON_DESIGN_TOGGLE_ON_48(); }
inline Image ICON_DESIGN_TUNE_48() { return UiIconsImg::ICON_DESIGN_TUNE_48(); }
inline Image ICON_DESIGN_TAB_48() { return UiIconsImg::ICON_DESIGN_TAB_48(); }
inline Image ICON_DESIGN_WIDGETS_48() { return UiIconsImg::ICON_DESIGN_WIDGETS_48(); }
inline Image ICON_DESIGN_COMMENT_48() { return UiIconsImg::ICON_DESIGN_COMMENT_48(); }
inline Image ICON_DESIGN_DESCRIPTION_48() { return UiIconsImg::ICON_DESIGN_DESCRIPTION_48(); }
inline Image ICON_DESIGN_FIND_REPLACE_48() { return UiIconsImg::ICON_DESIGN_FIND_REPLACE_48(); }
inline Image ICON_DESIGN_REMOVE_SELECTION_48() { return UiIconsImg::ICON_DESIGN_REMOVE_SELECTION_48(); }
inline Image ICON_DESIGN_TEXT_DECREASE_48() { return UiIconsImg::ICON_DESIGN_TEXT_DECREASE_48(); }
inline Image ICON_DESIGN_YOUTUBE_SEARCHED_FOR_48() { return UiIconsImg::ICON_DESIGN_YOUTUBE_SEARCHED_FOR_48(); }
inline Image ICON_DESIGN_FORMAT_PAINT_48() { return UiIconsImg::ICON_DESIGN_FORMAT_PAINT_48(); }
inline Image ICON_DESIGN_CODE_BLOCKS_48() { return UiIconsImg::ICON_DESIGN_CODE_BLOCKS_48(); }
inline Image ICON_DESIGN_HELP_48() { return UiIconsImg::ICON_DESIGN_HELP_48(); }
inline Image ICON_DESIGN_MODE_OFF_ON_48() { return UiIconsImg::ICON_DESIGN_MODE_OFF_ON_48(); }
inline Image ICON_DESIGN_OUTBOX_48() { return UiIconsImg::ICON_DESIGN_OUTBOX_48(); }
inline Image ICON_DESIGN_PUBLISH_48() { return UiIconsImg::ICON_DESIGN_PUBLISH_48(); }
inline Image ICON_DESIGN_SAVE_48() { return UiIconsImg::ICON_DESIGN_SAVE_48(); }
inline Image ICON_EDITOR_CLARIFY_48() { return UiIconsImg::ICON_EDITOR_CLARIFY_48(); }
inline Image ICON_EDITOR_FORMAT_BOLD_48() { return UiIconsImg::ICON_EDITOR_FORMAT_BOLD_48(); }
inline Image ICON_EDITOR_FORMAT_H1_48() { return UiIconsImg::ICON_EDITOR_FORMAT_H1_48(); }
inline Image ICON_EDITOR_FORMAT_H2_48() { return UiIconsImg::ICON_EDITOR_FORMAT_H2_48(); }
inline Image ICON_EDITOR_FORMAT_INDENT_DECREASE_48() { return UiIconsImg::ICON_EDITOR_FORMAT_INDENT_DECREASE_48(); }
inline Image ICON_EDITOR_FORMAT_INDENT_INCREASE_48() { return UiIconsImg::ICON_EDITOR_FORMAT_INDENT_INCREASE_48(); }
inline Image ICON_EDITOR_FORMAT_ITALIC_48() { return UiIconsImg::ICON_EDITOR_FORMAT_ITALIC_48(); }
inline Image ICON_EDITOR_FORMAT_LINE_SPACING_48() { return UiIconsImg::ICON_EDITOR_FORMAT_LINE_SPACING_48(); }
inline Image ICON_EDITOR_FORMAT_LIST_BULLETED_48() { return UiIconsImg::ICON_EDITOR_FORMAT_LIST_BULLETED_48(); }
inline Image ICON_EDITOR_FORMAT_LIST_NUMBERED_RTL_48() { return UiIconsImg::ICON_EDITOR_FORMAT_LIST_NUMBERED_RTL_48(); }
inline Image ICON_EDITOR_FORMAT_QUOTE_48() { return UiIconsImg::ICON_EDITOR_FORMAT_QUOTE_48(); }
inline Image ICON_EDITOR_FORMAT_STRIKETHROUGH_48() { return UiIconsImg::ICON_EDITOR_FORMAT_STRIKETHROUGH_48(); }
inline Image ICON_EDITOR_NOTES_48() { return UiIconsImg::ICON_EDITOR_NOTES_48(); }
inline Image ICON_EDITOR_SERIF_48() { return UiIconsImg::ICON_EDITOR_SERIF_48(); }
inline Image ICON_EDITOR_TABLE_48() { return UiIconsImg::ICON_EDITOR_TABLE_48(); }
inline Image ICON_TOGGLE_CHECK_BOX_48() { return UiIconsImg::ICON_TOGGLE_CHECK_BOX_48(); }
inline Image ICON_TOGGLE_RADIO_BUTTON_CHECKED_48() { return UiIconsImg::ICON_TOGGLE_RADIO_BUTTON_CHECKED_48(); }
inline Image ICON_MEDIA_FIRST_48() { return UiIconsImg::ICON_MEDIA_FIRST_48(); }
inline Image ICON_MEDIA_STEP_BACK_48() { return UiIconsImg::ICON_MEDIA_STEP_BACK_48(); }
inline Image ICON_MEDIA_REVERSE_48() { return UiIconsImg::ICON_MEDIA_REVERSE_48(); }
inline Image ICON_MEDIA_PAUSE_48() { return UiIconsImg::ICON_MEDIA_PAUSE_48(); }
inline Image ICON_MEDIA_PLAY_48() { return UiIconsImg::ICON_MEDIA_PLAY_48(); }
inline Image ICON_MEDIA_STEP_FORWARD_48() { return UiIconsImg::ICON_MEDIA_STEP_FORWARD_48(); }
inline Image ICON_MEDIA_LAST_48() { return UiIconsImg::ICON_MEDIA_LAST_48(); }
inline Image ICON_SAMPLE_POINT_48() { return UiIconsImg::ICON_SAMPLE_POINT_48(); }
inline Image ICON_SAMPLE_AREA_48() { return UiIconsImg::ICON_SAMPLE_AREA_48(); }
inline Image ICON_NAVIGATION_OUTLINED_MENU_48() { return UiIconsImg::ICON_NAVIGATION_OUTLINED_MENU_48(); }
inline Image ICON_NAVIGATION_OUTLINED_APPS_48() { return UiIconsImg::ICON_NAVIGATION_OUTLINED_APPS_48(); }
inline Image ICON_NAVIGATION_OUTLINED_DRAG_INDICATOR_48() { return UiIconsImg::ICON_NAVIGATION_OUTLINED_DRAG_INDICATOR_48(); }
inline Image ICON_NAVIGATION_EXIT_TO_APP_48() { return UiIconsImg::ICON_NAVIGATION_EXIT_TO_APP_48(); }
inline Image ICON_HARDWARE_OUTLINED_KEYBOARD_ARROW_LEFT_48() { return UiIconsImg::ICON_HARDWARE_OUTLINED_KEYBOARD_ARROW_LEFT_48(); }
inline Image ICON_CONTENT_OUTLINED_ADD_CIRCLE_OUTLINE_48() { return UiIconsImg::ICON_CONTENT_OUTLINED_ADD_CIRCLE_OUTLINE_48(); }
inline Image ICON_CONTENT_OUTLINED_REMOVE_CIRCLE_OUTLINE_48() { return UiIconsImg::ICON_CONTENT_OUTLINED_REMOVE_CIRCLE_OUTLINE_48(); }
inline Image ICON_CONTENT_OUTLINED_REMOVE_48() { return UiIconsImg::ICON_CONTENT_OUTLINED_REMOVE_48(); }
inline Image ICON_ACTION_CANCEL_48() { return UiIconsImg::ICON_ACTION_CANCEL_48(); }
inline Image ICON_ACTION_CHECK_CIRCLE_48() { return UiIconsImg::ICON_ACTION_CHECK_CIRCLE_48(); }
inline Image ICON_DESIGN_LEFT_PANEL_CLOSE_48() { return UiIconsImg::ICON_DESIGN_LEFT_PANEL_CLOSE_48(); }
inline Image ICON_DESIGN_LEFT_PANEL_OPEN_48() { return UiIconsImg::ICON_DESIGN_LEFT_PANEL_OPEN_48(); }
inline Image ICON_DESIGN_MENU_48() { return UiIconsImg::ICON_DESIGN_MENU_48(); }
inline Image ICON_DESIGN_RIGHT_PANEL_CLOSE_48() { return UiIconsImg::ICON_DESIGN_RIGHT_PANEL_CLOSE_48(); }
inline Image ICON_DESIGN_RIGHT_PANEL_OPEN_48() { return UiIconsImg::ICON_DESIGN_RIGHT_PANEL_OPEN_48(); }
inline Image ICON_DESIGN_UNFOLD_LESS_48() { return UiIconsImg::ICON_DESIGN_UNFOLD_LESS_48(); }
inline Image ICON_DESIGN_UNFOLD_MORE_48() { return UiIconsImg::ICON_DESIGN_UNFOLD_MORE_48(); }
inline Image ICON_DESIGN_CIRCLE_CIRCLE_48() { return UiIconsImg::ICON_DESIGN_CIRCLE_CIRCLE_48(); }
inline Image ICON_DESIGN_FIBER_MANUAL_RECORD_48() { return UiIconsImg::ICON_DESIGN_FIBER_MANUAL_RECORD_48(); }
inline Image ICON_DESIGN_BORDER_HORIZONTAL_48() { return UiIconsImg::ICON_DESIGN_BORDER_HORIZONTAL_48(); }
inline Image ICON_DESIGN_BORDER_INNER_48() { return UiIconsImg::ICON_DESIGN_BORDER_INNER_48(); }
inline Image ICON_DESIGN_BOTTOM_PANEL_CLOSE_48() { return UiIconsImg::ICON_DESIGN_BOTTOM_PANEL_CLOSE_48(); }
inline Image ICON_DESIGN_BOTTOM_PANEL_OPEN_48() { return UiIconsImg::ICON_DESIGN_BOTTOM_PANEL_OPEN_48(); }
inline Image ICON_DESIGN_BOTTOM_SHEETS_48() { return UiIconsImg::ICON_DESIGN_BOTTOM_SHEETS_48(); }
inline Image ICON_DESIGN_ID_CARD_48() { return UiIconsImg::ICON_DESIGN_ID_CARD_48(); }
inline Image ICON_DESIGN_LIST_ALT_48() { return UiIconsImg::ICON_DESIGN_LIST_ALT_48(); }
inline Image ICON_DESIGN_SPACE_DASHBOARD_48() { return UiIconsImg::ICON_DESIGN_SPACE_DASHBOARD_48(); }
inline Image ICON_DESIGN_BOX_LAYOUT_48() { return UiIconsImg::ICON_DESIGN_BOX_LAYOUT_48(); }
inline Image ICON_DESIGN_GRID_LAYOUT_48() { return UiIconsImg::ICON_DESIGN_GRID_LAYOUT_48(); }
inline Image ICON_DESIGN_PANEL_48() { return UiIconsImg::ICON_DESIGN_PANEL_48(); }
inline Image ICON_DESIGN_SCROLL_PANEL_48() { return UiIconsImg::ICON_DESIGN_SCROLL_PANEL_48(); }
inline Image ICON_DESIGN_TABLE_48() { return UiIconsImg::ICON_DESIGN_TABLE_48(); }
inline Image ICON_DESIGN_TREE_48() { return UiIconsImg::ICON_DESIGN_TREE_48(); }
inline Image ICON_DESIGN_TOGGLE_COMPOSITE_48() { return UiIconsImg::ICON_DESIGN_TOGGLE_COMPOSITE_48(); }
inline Image ICON_DESIGN_EDIT_TEXT_48() { return UiIconsImg::ICON_DESIGN_EDIT_TEXT_48(); }
inline Image ICON_DESIGN_EDIT_INT_48() { return UiIconsImg::ICON_DESIGN_EDIT_INT_48(); }
inline Image ICON_DESIGN_EDIT_FLOAT_48() { return UiIconsImg::ICON_DESIGN_EDIT_FLOAT_48(); }
inline Image ICON_DESIGN_STACK_48() { return UiIconsImg::ICON_DESIGN_STACK_48(); }
inline Image ICON_DESIGN_BUTTON_48() { return UiIconsImg::ICON_DESIGN_BUTTON_48(); }
inline Image ICON_DESIGN_BREADCRUMBS_48() { return UiIconsImg::ICON_DESIGN_BREADCRUMBS_48(); }
inline Image ICON_DESIGN_ARROWS_OUTPUT_48() { return UiIconsImg::ICON_DESIGN_ARROWS_OUTPUT_48(); }
inline Image ICON_DESIGN_ASPECT_RATIO_48() { return UiIconsImg::ICON_DESIGN_ASPECT_RATIO_48(); }
inline Image ICON_DESIGN_DASHBOARD_EDIT_48() { return UiIconsImg::ICON_DESIGN_DASHBOARD_EDIT_48(); }
inline Image ICON_DESIGN_DASHBOARD_CUSTOMIZE_48() { return UiIconsImg::ICON_DESIGN_DASHBOARD_CUSTOMIZE_48(); }
inline Image ICON_DESIGN_DYNAMIC_FORM_48() { return UiIconsImg::ICON_DESIGN_DYNAMIC_FORM_48(); }
inline Image ICON_DESIGN_EXPANSION_PANELS_48() { return UiIconsImg::ICON_DESIGN_EXPANSION_PANELS_48(); }
inline Image ICON_DESIGN_FIT_PAGE_48() { return UiIconsImg::ICON_DESIGN_FIT_PAGE_48(); }
inline Image ICON_DESIGN_FIT_WIDTH_48() { return UiIconsImg::ICON_DESIGN_FIT_WIDTH_48(); }
inline Image ICON_DESIGN_GRID_4X4_48() { return UiIconsImg::ICON_DESIGN_GRID_4X4_48(); }
inline Image ICON_DESIGN_HORIZONTAL_DISTRIBUTE_48() { return UiIconsImg::ICON_DESIGN_HORIZONTAL_DISTRIBUTE_48(); }
inline Image ICON_DESIGN_LAYOUTS_CATEGORY_48() { return UiIconsImg::ICON_DESIGN_LAYOUTS_CATEGORY_48(); }
inline Image ICON_DESIGN_SLIDERS_48() { return UiIconsImg::ICON_DESIGN_SLIDERS_48(); }
inline Image ICON_DESIGN_TAB_GROUP_48() { return UiIconsImg::ICON_DESIGN_TAB_GROUP_48(); }
inline Image ICON_DESIGN_VERTICAL_DISTRIBUTE_48() { return UiIconsImg::ICON_DESIGN_VERTICAL_DISTRIBUTE_48(); }
inline Image ICON_DESIGN_BORDER_ALL_48() { return UiIconsImg::ICON_DESIGN_BORDER_ALL_48(); }
inline Image ICON_DESIGN_BORDER_OUTER_48() { return UiIconsImg::ICON_DESIGN_BORDER_OUTER_48(); }
inline Image ICON_DESIGN_BORDER_CLEAR_48() { return UiIconsImg::ICON_DESIGN_BORDER_CLEAR_48(); }
inline Image ICON_DESIGN_SQUARE_DOT_48() { return UiIconsImg::ICON_DESIGN_SQUARE_DOT_48(); }
inline Image ICON_DESIGN_ARROW_CIRCLE_LEFT_48() { return UiIconsImg::ICON_DESIGN_ARROW_CIRCLE_LEFT_48(); }
inline Image ICON_DESIGN_FULL_STACKED_BAR_CHART_48() { return UiIconsImg::ICON_DESIGN_FULL_STACKED_BAR_CHART_48(); }
inline Image ICON_DESIGN_TOOLBAR_48() { return UiIconsImg::ICON_DESIGN_TOOLBAR_48(); }
inline Image ICON_DESIGN_DESKTOP_MAC_48() { return UiIconsImg::ICON_DESIGN_DESKTOP_MAC_48(); }
inline Image ICON_DESIGN_SPLITSCREEN_LANDSCAPE_48() { return UiIconsImg::ICON_DESIGN_SPLITSCREEN_LANDSCAPE_48(); }
inline Image ICON_DESIGN_SPLITSCREEN_PORTRAIT_48() { return UiIconsImg::ICON_DESIGN_SPLITSCREEN_PORTRAIT_48(); }
inline Image ICON_DESIGN_CUSTOM_TYPOGRAPHY_48() { return UiIconsImg::ICON_DESIGN_CUSTOM_TYPOGRAPHY_48(); }
inline Image ICON_DESIGN_INFO_48() { return UiIconsImg::ICON_DESIGN_INFO_48(); }
inline Image ICON_DESIGN_CANCEL_48() { return UiIconsImg::ICON_DESIGN_CANCEL_48(); }
inline Image ICON_DESIGN_CLEAR_ALL_48() { return UiIconsImg::ICON_DESIGN_CLEAR_ALL_48(); }
inline Image ICON_DESIGN_DOWNLOAD_48() { return UiIconsImg::ICON_DESIGN_DOWNLOAD_48(); }
inline Image ICON_DESIGN_DOWNLOAD_FOR_OFFLINE_48() { return UiIconsImg::ICON_DESIGN_DOWNLOAD_FOR_OFFLINE_48(); }
inline Image ICON_DESIGN_PENDING_48() { return UiIconsImg::ICON_DESIGN_PENDING_48(); }
inline Image ICON_DESIGN_STORAGE_48() { return UiIconsImg::ICON_DESIGN_STORAGE_48(); }
inline Image ICON_DESIGN_SYSTEM_UPDATE_ALT_48() { return UiIconsImg::ICON_DESIGN_SYSTEM_UPDATE_ALT_48(); }
inline Image ICON_DESIGN_UPLOAD_48() { return UiIconsImg::ICON_DESIGN_UPLOAD_48(); }
inline Image ICON_EDITOR_BORDER_LEFT_48() { return UiIconsImg::ICON_EDITOR_BORDER_LEFT_48(); }
inline Image ICON_EDITOR_BORDER_RIGHT_48() { return UiIconsImg::ICON_EDITOR_BORDER_RIGHT_48(); }
inline Image ICON_EDITOR_FORMAT_ALIGN_CENTER_48() { return UiIconsImg::ICON_EDITOR_FORMAT_ALIGN_CENTER_48(); }
inline Image ICON_EDITOR_FORMAT_ALIGN_JUSTIFY_48() { return UiIconsImg::ICON_EDITOR_FORMAT_ALIGN_JUSTIFY_48(); }
inline Image ICON_EDITOR_FORMAT_ALIGN_LEFT_48() { return UiIconsImg::ICON_EDITOR_FORMAT_ALIGN_LEFT_48(); }
inline Image ICON_EDITOR_FORMAT_ALIGN_RIGHT_48() { return UiIconsImg::ICON_EDITOR_FORMAT_ALIGN_RIGHT_48(); }
inline Image ICON_EDITOR_FORMAT_H3_48() { return UiIconsImg::ICON_EDITOR_FORMAT_H3_48(); }
inline Image ICON_EDITOR_FORMAT_LETTER_SPACING_STANDARD_48() { return UiIconsImg::ICON_EDITOR_FORMAT_LETTER_SPACING_STANDARD_48(); }
inline Image ICON_EDITOR_FORMAT_SIZE_48() { return UiIconsImg::ICON_EDITOR_FORMAT_SIZE_48(); }
inline Image ICON_EDITOR_MARGIN_48() { return UiIconsImg::ICON_EDITOR_MARGIN_48(); }
inline Image ICON_EDITOR_TITLECASE_48() { return UiIconsImg::ICON_EDITOR_TITLECASE_48(); }
inline Image ICON_COMMUNICATION_COMMENT_48() { return UiIconsImg::ICON_COMMUNICATION_COMMENT_48(); }
inline Image ICON_TOGGLE_CHECK_BOX_OUTLINE_BLANK_48() { return UiIconsImg::ICON_TOGGLE_CHECK_BOX_OUTLINE_BLANK_48(); }
inline Image ICON_TOGGLE_RADIO_BUTTON_UNCHECKED_48() { return UiIconsImg::ICON_TOGGLE_RADIO_BUTTON_UNCHECKED_48(); }
inline Image ICON_ACTION_FIT_SCREEN_OUTLINED() { return UiIconsImg::ICON_ACTION_FIT_SCREEN_OUTLINED(); }
inline Image ICON_IMAGE_RESET_SHADOW_OUTLINED() { return UiIconsImg::ICON_IMAGE_RESET_SHADOW_OUTLINED(); }
inline Image ICON_IMAGES_UPP_HEADING_ICON_OUTLINED() { return UiIconsImg::ICON_IMAGES_UPP_HEADING_ICON_OUTLINED(); }
inline Image ICON_IMAGE_VIEW_REAL_SIZE_OUTLINED() { return UiIconsImg::ICON_IMAGE_VIEW_REAL_SIZE_OUTLINED(); }
inline Image ICON_BUSINES_GRAPH_1_OUTLINED() { return UiIconsImg::ICON_BUSINES_GRAPH_1_OUTLINED(); }
inline Image ICON_UI_ACTION_RECENTER_OUTLINED() { return UiIconsImg::ICON_UI_ACTION_RECENTER_OUTLINED(); }
inline Image ICON_DESIGN_TRIP_ORIGIN_48() { return UiIconsImg::ICON_DESIGN_TRIP_ORIGIN_48(); }
inline Image ICON_EDITOR_MODE_OFF_ON_48() { return UiIconsImg::ICON_EDITOR_MODE_OFF_ON_48(); }
inline Image ICON_ACTION_REORDER_OUTLINED() { return UiIconsImg::ICON_ACTION_REORDER_OUTLINED(); }
inline Image ICON_ACTION_ARROW_CIRCLE_DOWN_OUTLINED() { return UiIconsImg::ICON_ACTION_ARROW_CIRCLE_DOWN_OUTLINED(); }
inline Image ICON_ACTION_ARROW_CIRCLE_RIGHT_OUTLINED() { return UiIconsImg::ICON_ACTION_ARROW_CIRCLE_RIGHT_OUTLINED(); }
inline Image ICON_ACTION_ARROW_CIRCLE_UP_OUTLINED() { return UiIconsImg::ICON_ACTION_ARROW_CIRCLE_UP_OUTLINED(); }
inline Image ICON_UI_ACTION_SWAP_VERTICAL_CIRCLE_OUTLINED() { return UiIconsImg::ICON_UI_ACTION_SWAP_VERTICAL_CIRCLE_OUTLINED(); }
inline Image ICON_BRAND_NEWLOGO_V5_48() { return UiIconsImg::ICON_BRAND_NEWLOGO_V5_48(); }
inline Image ICON_EDITOR_BORDER_VERTICAL_OUTLINED() { return UiIconsImg::ICON_EDITOR_BORDER_VERTICAL_OUTLINED(); }

struct UIICONSCatalogEntry {
	const char* category;
	const char* display_name;
	const char* symbol_name;
	Image (*factory)();
};

inline const UIICONSCatalogEntry* GetUIICONSCatalog(int& count)
{
	static const UIICONSCatalogEntry catalog[] = {
		{ "NAVIGATION", "ICON_NAVIGATION_OUTLINED_MORE_HORIZ_48", "ICON_NAVIGATION_OUTLINED_MORE_HORIZ_48", &ICON_NAVIGATION_OUTLINED_MORE_HORIZ_48 },
		{ "NAVIGATION", "ICON_NAVIGATION_OUTLINED_MORE_VERT_48", "ICON_NAVIGATION_OUTLINED_MORE_VERT_48", &ICON_NAVIGATION_OUTLINED_MORE_VERT_48 },
		{ "NAVIGATION", "ICON_NAVIGATION_OUTLINED_ARROW_RIGHT_48", "ICON_NAVIGATION_OUTLINED_ARROW_RIGHT_48", &ICON_NAVIGATION_OUTLINED_ARROW_RIGHT_48 },
		{ "NAVIGATION", "ICON_NAVIGATION_OUTLINED_ARROW_LEFT_48", "ICON_NAVIGATION_OUTLINED_ARROW_LEFT_48", &ICON_NAVIGATION_OUTLINED_ARROW_LEFT_48 },
		{ "NAVIGATION", "ICON_NAVIGATION_OUTLINED_ARROW_DROP_UP_48", "ICON_NAVIGATION_OUTLINED_ARROW_DROP_UP_48", &ICON_NAVIGATION_OUTLINED_ARROW_DROP_UP_48 },
		{ "NAVIGATION", "ICON_NAVIGATION_OUTLINED_ARROW_DROP_DOWN_48", "ICON_NAVIGATION_OUTLINED_ARROW_DROP_DOWN_48", &ICON_NAVIGATION_OUTLINED_ARROW_DROP_DOWN_48 },
		{ "NAVIGATION", "ICON_NAVIGATION_CLOSE_SMALL_48", "ICON_NAVIGATION_CLOSE_SMALL_48", &ICON_NAVIGATION_CLOSE_SMALL_48 },
		{ "HARDWARE", "ICON_HARDWARE_OUTLINED_KEYBOARD_ARROW_RIGHT_48", "ICON_HARDWARE_OUTLINED_KEYBOARD_ARROW_RIGHT_48", &ICON_HARDWARE_OUTLINED_KEYBOARD_ARROW_RIGHT_48 },
		{ "CONTENT", "ICON_CONTENT_OUTLINED_ADD_48", "ICON_CONTENT_OUTLINED_ADD_48", &ICON_CONTENT_OUTLINED_ADD_48 },
		{ "CONTENT", "ICON_CONTENT_CONTENT_COPY_48", "ICON_CONTENT_CONTENT_COPY_48", &ICON_CONTENT_CONTENT_COPY_48 },
		{ "ACTION", "ICON_ACTION_OUTLINED_VISIBILITY_48", "ICON_ACTION_OUTLINED_VISIBILITY_48", &ICON_ACTION_OUTLINED_VISIBILITY_48 },
		{ "ACTION", "ICON_ACTION_OUTLINED_VISIBILITY_OFF_48", "ICON_ACTION_OUTLINED_VISIBILITY_OFF_48", &ICON_ACTION_OUTLINED_VISIBILITY_OFF_48 },
		{ "ACTION", "ICON_ACTION_SEARCH_48", "ICON_ACTION_SEARCH_48", &ICON_ACTION_SEARCH_48 },
		{ "ACTION", "ICON_ACTION_DARK_MODE_48", "ICON_ACTION_DARK_MODE_48", &ICON_ACTION_DARK_MODE_48 },
		{ "ACTION", "ICON_ACTION_LIGHT_MODE_48", "ICON_ACTION_LIGHT_MODE_48", &ICON_ACTION_LIGHT_MODE_48 },
		{ "DESIGN", "ICON_DESIGN_CHECK_SMALL_48", "ICON_DESIGN_CHECK_SMALL_48", &ICON_DESIGN_CHECK_SMALL_48 },
		{ "DESIGN", "ICON_DESIGN_DELETE_48", "ICON_DESIGN_DELETE_48", &ICON_DESIGN_DELETE_48 },
		{ "DESIGN", "ICON_DESIGN_DRAG_INDICATOR_48", "ICON_DESIGN_DRAG_INDICATOR_48", &ICON_DESIGN_DRAG_INDICATOR_48 },
		{ "DESIGN", "ICON_DESIGN_FOLDER_48", "ICON_DESIGN_FOLDER_48", &ICON_DESIGN_FOLDER_48 },
		{ "DESIGN", "ICON_DESIGN_HOME_48", "ICON_DESIGN_HOME_48", &ICON_DESIGN_HOME_48 },
		{ "DESIGN", "ICON_DESIGN_IMAGE_48", "ICON_DESIGN_IMAGE_48", &ICON_DESIGN_IMAGE_48 },
		{ "DESIGN", "ICON_DESIGN_LOWERCASE_48", "ICON_DESIGN_LOWERCASE_48", &ICON_DESIGN_LOWERCASE_48 },
		{ "DESIGN", "ICON_DESIGN_SETTINGS_48", "ICON_DESIGN_SETTINGS_48", &ICON_DESIGN_SETTINGS_48 },
		{ "DESIGN", "ICON_DESIGN_UPPERCASE_48", "ICON_DESIGN_UPPERCASE_48", &ICON_DESIGN_UPPERCASE_48 },
		{ "DESIGN", "ICON_DESIGN_ADJUST_48", "ICON_DESIGN_ADJUST_48", &ICON_DESIGN_ADJUST_48 },
		{ "DESIGN", "ICON_DESIGN_CIRCLE_48", "ICON_DESIGN_CIRCLE_48", &ICON_DESIGN_CIRCLE_48 },
		{ "DESIGN", "ICON_DESIGN_ACCOUNT_TREE_48", "ICON_DESIGN_ACCOUNT_TREE_48", &ICON_DESIGN_ACCOUNT_TREE_48 },
		{ "DESIGN", "ICON_DESIGN_LABEL_48", "ICON_DESIGN_LABEL_48", &ICON_DESIGN_LABEL_48 },
		{ "DESIGN", "ICON_DESIGN_TOGGLE_ON_48", "ICON_DESIGN_TOGGLE_ON_48", &ICON_DESIGN_TOGGLE_ON_48 },
		{ "DESIGN", "ICON_DESIGN_TUNE_48", "ICON_DESIGN_TUNE_48", &ICON_DESIGN_TUNE_48 },
		{ "DESIGN", "ICON_DESIGN_TAB_48", "ICON_DESIGN_TAB_48", &ICON_DESIGN_TAB_48 },
		{ "DESIGN", "ICON_DESIGN_WIDGETS_48", "ICON_DESIGN_WIDGETS_48", &ICON_DESIGN_WIDGETS_48 },
		{ "DESIGN", "ICON_DESIGN_COMMENT_48", "ICON_DESIGN_COMMENT_48", &ICON_DESIGN_COMMENT_48 },
		{ "DESIGN", "ICON_DESIGN_DESCRIPTION_48", "ICON_DESIGN_DESCRIPTION_48", &ICON_DESIGN_DESCRIPTION_48 },
		{ "DESIGN", "ICON_DESIGN_FIND_REPLACE_48", "ICON_DESIGN_FIND_REPLACE_48", &ICON_DESIGN_FIND_REPLACE_48 },
		{ "DESIGN", "ICON_DESIGN_REMOVE_SELECTION_48", "ICON_DESIGN_REMOVE_SELECTION_48", &ICON_DESIGN_REMOVE_SELECTION_48 },
		{ "DESIGN", "ICON_DESIGN_TEXT_DECREASE_48", "ICON_DESIGN_TEXT_DECREASE_48", &ICON_DESIGN_TEXT_DECREASE_48 },
		{ "DESIGN", "ICON_DESIGN_YOUTUBE_SEARCHED_FOR_48", "ICON_DESIGN_YOUTUBE_SEARCHED_FOR_48", &ICON_DESIGN_YOUTUBE_SEARCHED_FOR_48 },
		{ "DESIGN", "ICON_DESIGN_FORMAT_PAINT_48", "ICON_DESIGN_FORMAT_PAINT_48", &ICON_DESIGN_FORMAT_PAINT_48 },
		{ "DESIGN", "ICON_DESIGN_CODE_BLOCKS_48", "ICON_DESIGN_CODE_BLOCKS_48", &ICON_DESIGN_CODE_BLOCKS_48 },
		{ "DESIGN", "ICON_DESIGN_HELP_48", "ICON_DESIGN_HELP_48", &ICON_DESIGN_HELP_48 },
		{ "DESIGN", "ICON_DESIGN_MODE_OFF_ON_48", "ICON_DESIGN_MODE_OFF_ON_48", &ICON_DESIGN_MODE_OFF_ON_48 },
		{ "DESIGN", "ICON_DESIGN_OUTBOX_48", "ICON_DESIGN_OUTBOX_48", &ICON_DESIGN_OUTBOX_48 },
		{ "DESIGN", "ICON_DESIGN_PUBLISH_48", "ICON_DESIGN_PUBLISH_48", &ICON_DESIGN_PUBLISH_48 },
		{ "DESIGN", "ICON_DESIGN_SAVE_48", "ICON_DESIGN_SAVE_48", &ICON_DESIGN_SAVE_48 },
		{ "EDITOR", "ICON_EDITOR_CLARIFY_48", "ICON_EDITOR_CLARIFY_48", &ICON_EDITOR_CLARIFY_48 },
		{ "EDITOR", "ICON_EDITOR_FORMAT_BOLD_48", "ICON_EDITOR_FORMAT_BOLD_48", &ICON_EDITOR_FORMAT_BOLD_48 },
		{ "EDITOR", "ICON_EDITOR_FORMAT_H1_48", "ICON_EDITOR_FORMAT_H1_48", &ICON_EDITOR_FORMAT_H1_48 },
		{ "EDITOR", "ICON_EDITOR_FORMAT_H2_48", "ICON_EDITOR_FORMAT_H2_48", &ICON_EDITOR_FORMAT_H2_48 },
		{ "EDITOR", "ICON_EDITOR_FORMAT_INDENT_DECREASE_48", "ICON_EDITOR_FORMAT_INDENT_DECREASE_48", &ICON_EDITOR_FORMAT_INDENT_DECREASE_48 },
		{ "EDITOR", "ICON_EDITOR_FORMAT_INDENT_INCREASE_48", "ICON_EDITOR_FORMAT_INDENT_INCREASE_48", &ICON_EDITOR_FORMAT_INDENT_INCREASE_48 },
		{ "EDITOR", "ICON_EDITOR_FORMAT_ITALIC_48", "ICON_EDITOR_FORMAT_ITALIC_48", &ICON_EDITOR_FORMAT_ITALIC_48 },
		{ "EDITOR", "ICON_EDITOR_FORMAT_LINE_SPACING_48", "ICON_EDITOR_FORMAT_LINE_SPACING_48", &ICON_EDITOR_FORMAT_LINE_SPACING_48 },
		{ "EDITOR", "ICON_EDITOR_FORMAT_LIST_BULLETED_48", "ICON_EDITOR_FORMAT_LIST_BULLETED_48", &ICON_EDITOR_FORMAT_LIST_BULLETED_48 },
		{ "EDITOR", "ICON_EDITOR_FORMAT_LIST_NUMBERED_RTL_48", "ICON_EDITOR_FORMAT_LIST_NUMBERED_RTL_48", &ICON_EDITOR_FORMAT_LIST_NUMBERED_RTL_48 },
		{ "EDITOR", "ICON_EDITOR_FORMAT_QUOTE_48", "ICON_EDITOR_FORMAT_QUOTE_48", &ICON_EDITOR_FORMAT_QUOTE_48 },
		{ "EDITOR", "ICON_EDITOR_FORMAT_STRIKETHROUGH_48", "ICON_EDITOR_FORMAT_STRIKETHROUGH_48", &ICON_EDITOR_FORMAT_STRIKETHROUGH_48 },
		{ "EDITOR", "ICON_EDITOR_NOTES_48", "ICON_EDITOR_NOTES_48", &ICON_EDITOR_NOTES_48 },
		{ "EDITOR", "ICON_EDITOR_SERIF_48", "ICON_EDITOR_SERIF_48", &ICON_EDITOR_SERIF_48 },
		{ "EDITOR", "ICON_EDITOR_TABLE_48", "ICON_EDITOR_TABLE_48", &ICON_EDITOR_TABLE_48 },
		{ "TOGGLE", "ICON_TOGGLE_CHECK_BOX_48", "ICON_TOGGLE_CHECK_BOX_48", &ICON_TOGGLE_CHECK_BOX_48 },
		{ "TOGGLE", "ICON_TOGGLE_RADIO_BUTTON_CHECKED_48", "ICON_TOGGLE_RADIO_BUTTON_CHECKED_48", &ICON_TOGGLE_RADIO_BUTTON_CHECKED_48 },
		{ "MEDIA", "ICON_MEDIA_FIRST_48", "ICON_MEDIA_FIRST_48", &ICON_MEDIA_FIRST_48 },
		{ "MEDIA", "ICON_MEDIA_STEP_BACK_48", "ICON_MEDIA_STEP_BACK_48", &ICON_MEDIA_STEP_BACK_48 },
		{ "MEDIA", "ICON_MEDIA_REVERSE_48", "ICON_MEDIA_REVERSE_48", &ICON_MEDIA_REVERSE_48 },
		{ "MEDIA", "ICON_MEDIA_PAUSE_48", "ICON_MEDIA_PAUSE_48", &ICON_MEDIA_PAUSE_48 },
		{ "MEDIA", "ICON_MEDIA_PLAY_48", "ICON_MEDIA_PLAY_48", &ICON_MEDIA_PLAY_48 },
		{ "MEDIA", "ICON_MEDIA_STEP_FORWARD_48", "ICON_MEDIA_STEP_FORWARD_48", &ICON_MEDIA_STEP_FORWARD_48 },
		{ "MEDIA", "ICON_MEDIA_LAST_48", "ICON_MEDIA_LAST_48", &ICON_MEDIA_LAST_48 },
		{ "SAMPLE", "ICON_SAMPLE_POINT_48", "ICON_SAMPLE_POINT_48", &ICON_SAMPLE_POINT_48 },
		{ "SAMPLE", "ICON_SAMPLE_AREA_48", "ICON_SAMPLE_AREA_48", &ICON_SAMPLE_AREA_48 },
		{ "Compatibility / NAVIGATION", "ICON_NAVIGATION_OUTLINED_MENU_48", "ICON_NAVIGATION_OUTLINED_MENU_48", &ICON_NAVIGATION_OUTLINED_MENU_48 },
		{ "Compatibility / NAVIGATION", "ICON_NAVIGATION_OUTLINED_APPS_48", "ICON_NAVIGATION_OUTLINED_APPS_48", &ICON_NAVIGATION_OUTLINED_APPS_48 },
		{ "Compatibility / NAVIGATION", "ICON_NAVIGATION_OUTLINED_DRAG_INDICATOR_48", "ICON_NAVIGATION_OUTLINED_DRAG_INDICATOR_48", &ICON_NAVIGATION_OUTLINED_DRAG_INDICATOR_48 },
		{ "Compatibility / NAVIGATION", "ICON_NAVIGATION_EXIT_TO_APP_48", "ICON_NAVIGATION_EXIT_TO_APP_48", &ICON_NAVIGATION_EXIT_TO_APP_48 },
		{ "Compatibility / HARDWARE", "ICON_HARDWARE_OUTLINED_KEYBOARD_ARROW_LEFT_48", "ICON_HARDWARE_OUTLINED_KEYBOARD_ARROW_LEFT_48", &ICON_HARDWARE_OUTLINED_KEYBOARD_ARROW_LEFT_48 },
		{ "Compatibility / CONTENT", "ICON_CONTENT_OUTLINED_ADD_CIRCLE_OUTLINE_48", "ICON_CONTENT_OUTLINED_ADD_CIRCLE_OUTLINE_48", &ICON_CONTENT_OUTLINED_ADD_CIRCLE_OUTLINE_48 },
		{ "Compatibility / CONTENT", "ICON_CONTENT_OUTLINED_REMOVE_CIRCLE_OUTLINE_48", "ICON_CONTENT_OUTLINED_REMOVE_CIRCLE_OUTLINE_48", &ICON_CONTENT_OUTLINED_REMOVE_CIRCLE_OUTLINE_48 },
		{ "Compatibility / CONTENT", "ICON_CONTENT_OUTLINED_REMOVE_48", "ICON_CONTENT_OUTLINED_REMOVE_48", &ICON_CONTENT_OUTLINED_REMOVE_48 },
		{ "Compatibility / ACTION", "ICON_ACTION_CANCEL_48", "ICON_ACTION_CANCEL_48", &ICON_ACTION_CANCEL_48 },
		{ "Compatibility / ACTION", "ICON_ACTION_CHECK_CIRCLE_48", "ICON_ACTION_CHECK_CIRCLE_48", &ICON_ACTION_CHECK_CIRCLE_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_LEFT_PANEL_CLOSE_48", "ICON_DESIGN_LEFT_PANEL_CLOSE_48", &ICON_DESIGN_LEFT_PANEL_CLOSE_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_LEFT_PANEL_OPEN_48", "ICON_DESIGN_LEFT_PANEL_OPEN_48", &ICON_DESIGN_LEFT_PANEL_OPEN_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_MENU_48", "ICON_DESIGN_MENU_48", &ICON_DESIGN_MENU_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_RIGHT_PANEL_CLOSE_48", "ICON_DESIGN_RIGHT_PANEL_CLOSE_48", &ICON_DESIGN_RIGHT_PANEL_CLOSE_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_RIGHT_PANEL_OPEN_48", "ICON_DESIGN_RIGHT_PANEL_OPEN_48", &ICON_DESIGN_RIGHT_PANEL_OPEN_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_UNFOLD_LESS_48", "ICON_DESIGN_UNFOLD_LESS_48", &ICON_DESIGN_UNFOLD_LESS_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_UNFOLD_MORE_48", "ICON_DESIGN_UNFOLD_MORE_48", &ICON_DESIGN_UNFOLD_MORE_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_CIRCLE_CIRCLE_48", "ICON_DESIGN_CIRCLE_CIRCLE_48", &ICON_DESIGN_CIRCLE_CIRCLE_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_FIBER_MANUAL_RECORD_48", "ICON_DESIGN_FIBER_MANUAL_RECORD_48", &ICON_DESIGN_FIBER_MANUAL_RECORD_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_BORDER_HORIZONTAL_48", "ICON_DESIGN_BORDER_HORIZONTAL_48", &ICON_DESIGN_BORDER_HORIZONTAL_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_BORDER_INNER_48", "ICON_DESIGN_BORDER_INNER_48", &ICON_DESIGN_BORDER_INNER_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_BOTTOM_PANEL_CLOSE_48", "ICON_DESIGN_BOTTOM_PANEL_CLOSE_48", &ICON_DESIGN_BOTTOM_PANEL_CLOSE_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_BOTTOM_PANEL_OPEN_48", "ICON_DESIGN_BOTTOM_PANEL_OPEN_48", &ICON_DESIGN_BOTTOM_PANEL_OPEN_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_BOTTOM_SHEETS_48", "ICON_DESIGN_BOTTOM_SHEETS_48", &ICON_DESIGN_BOTTOM_SHEETS_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_ID_CARD_48", "ICON_DESIGN_ID_CARD_48", &ICON_DESIGN_ID_CARD_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_LIST_ALT_48", "ICON_DESIGN_LIST_ALT_48", &ICON_DESIGN_LIST_ALT_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_SPACE_DASHBOARD_48", "ICON_DESIGN_SPACE_DASHBOARD_48", &ICON_DESIGN_SPACE_DASHBOARD_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_BOX_LAYOUT_48", "ICON_DESIGN_BOX_LAYOUT_48", &ICON_DESIGN_BOX_LAYOUT_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_GRID_LAYOUT_48", "ICON_DESIGN_GRID_LAYOUT_48", &ICON_DESIGN_GRID_LAYOUT_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_PANEL_48", "ICON_DESIGN_PANEL_48", &ICON_DESIGN_PANEL_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_SCROLL_PANEL_48", "ICON_DESIGN_SCROLL_PANEL_48", &ICON_DESIGN_SCROLL_PANEL_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_TABLE_48", "ICON_DESIGN_TABLE_48", &ICON_DESIGN_TABLE_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_TREE_48", "ICON_DESIGN_TREE_48", &ICON_DESIGN_TREE_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_TOGGLE_COMPOSITE_48", "ICON_DESIGN_TOGGLE_COMPOSITE_48", &ICON_DESIGN_TOGGLE_COMPOSITE_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_EDIT_TEXT_48", "ICON_DESIGN_EDIT_TEXT_48", &ICON_DESIGN_EDIT_TEXT_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_EDIT_INT_48", "ICON_DESIGN_EDIT_INT_48", &ICON_DESIGN_EDIT_INT_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_EDIT_FLOAT_48", "ICON_DESIGN_EDIT_FLOAT_48", &ICON_DESIGN_EDIT_FLOAT_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_STACK_48", "ICON_DESIGN_STACK_48", &ICON_DESIGN_STACK_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_BUTTON_48", "ICON_DESIGN_BUTTON_48", &ICON_DESIGN_BUTTON_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_BREADCRUMBS_48", "ICON_DESIGN_BREADCRUMBS_48", &ICON_DESIGN_BREADCRUMBS_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_ARROWS_OUTPUT_48", "ICON_DESIGN_ARROWS_OUTPUT_48", &ICON_DESIGN_ARROWS_OUTPUT_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_ASPECT_RATIO_48", "ICON_DESIGN_ASPECT_RATIO_48", &ICON_DESIGN_ASPECT_RATIO_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_DASHBOARD_EDIT_48", "ICON_DESIGN_DASHBOARD_EDIT_48", &ICON_DESIGN_DASHBOARD_EDIT_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_DASHBOARD_CUSTOMIZE_48", "ICON_DESIGN_DASHBOARD_CUSTOMIZE_48", &ICON_DESIGN_DASHBOARD_CUSTOMIZE_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_DYNAMIC_FORM_48", "ICON_DESIGN_DYNAMIC_FORM_48", &ICON_DESIGN_DYNAMIC_FORM_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_EXPANSION_PANELS_48", "ICON_DESIGN_EXPANSION_PANELS_48", &ICON_DESIGN_EXPANSION_PANELS_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_FIT_PAGE_48", "ICON_DESIGN_FIT_PAGE_48", &ICON_DESIGN_FIT_PAGE_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_FIT_WIDTH_48", "ICON_DESIGN_FIT_WIDTH_48", &ICON_DESIGN_FIT_WIDTH_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_GRID_4X4_48", "ICON_DESIGN_GRID_4X4_48", &ICON_DESIGN_GRID_4X4_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_HORIZONTAL_DISTRIBUTE_48", "ICON_DESIGN_HORIZONTAL_DISTRIBUTE_48", &ICON_DESIGN_HORIZONTAL_DISTRIBUTE_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_LAYOUTS_CATEGORY_48", "ICON_DESIGN_LAYOUTS_CATEGORY_48", &ICON_DESIGN_LAYOUTS_CATEGORY_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_SLIDERS_48", "ICON_DESIGN_SLIDERS_48", &ICON_DESIGN_SLIDERS_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_TAB_GROUP_48", "ICON_DESIGN_TAB_GROUP_48", &ICON_DESIGN_TAB_GROUP_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_VERTICAL_DISTRIBUTE_48", "ICON_DESIGN_VERTICAL_DISTRIBUTE_48", &ICON_DESIGN_VERTICAL_DISTRIBUTE_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_BORDER_ALL_48", "ICON_DESIGN_BORDER_ALL_48", &ICON_DESIGN_BORDER_ALL_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_BORDER_OUTER_48", "ICON_DESIGN_BORDER_OUTER_48", &ICON_DESIGN_BORDER_OUTER_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_BORDER_CLEAR_48", "ICON_DESIGN_BORDER_CLEAR_48", &ICON_DESIGN_BORDER_CLEAR_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_SQUARE_DOT_48", "ICON_DESIGN_SQUARE_DOT_48", &ICON_DESIGN_SQUARE_DOT_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_ARROW_CIRCLE_LEFT_48", "ICON_DESIGN_ARROW_CIRCLE_LEFT_48", &ICON_DESIGN_ARROW_CIRCLE_LEFT_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_FULL_STACKED_BAR_CHART_48", "ICON_DESIGN_FULL_STACKED_BAR_CHART_48", &ICON_DESIGN_FULL_STACKED_BAR_CHART_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_TOOLBAR_48", "ICON_DESIGN_TOOLBAR_48", &ICON_DESIGN_TOOLBAR_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_DESKTOP_MAC_48", "ICON_DESIGN_DESKTOP_MAC_48", &ICON_DESIGN_DESKTOP_MAC_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_SPLITSCREEN_LANDSCAPE_48", "ICON_DESIGN_SPLITSCREEN_LANDSCAPE_48", &ICON_DESIGN_SPLITSCREEN_LANDSCAPE_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_SPLITSCREEN_PORTRAIT_48", "ICON_DESIGN_SPLITSCREEN_PORTRAIT_48", &ICON_DESIGN_SPLITSCREEN_PORTRAIT_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_CUSTOM_TYPOGRAPHY_48", "ICON_DESIGN_CUSTOM_TYPOGRAPHY_48", &ICON_DESIGN_CUSTOM_TYPOGRAPHY_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_INFO_48", "ICON_DESIGN_INFO_48", &ICON_DESIGN_INFO_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_CANCEL_48", "ICON_DESIGN_CANCEL_48", &ICON_DESIGN_CANCEL_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_CLEAR_ALL_48", "ICON_DESIGN_CLEAR_ALL_48", &ICON_DESIGN_CLEAR_ALL_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_DOWNLOAD_48", "ICON_DESIGN_DOWNLOAD_48", &ICON_DESIGN_DOWNLOAD_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_DOWNLOAD_FOR_OFFLINE_48", "ICON_DESIGN_DOWNLOAD_FOR_OFFLINE_48", &ICON_DESIGN_DOWNLOAD_FOR_OFFLINE_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_PENDING_48", "ICON_DESIGN_PENDING_48", &ICON_DESIGN_PENDING_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_STORAGE_48", "ICON_DESIGN_STORAGE_48", &ICON_DESIGN_STORAGE_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_SYSTEM_UPDATE_ALT_48", "ICON_DESIGN_SYSTEM_UPDATE_ALT_48", &ICON_DESIGN_SYSTEM_UPDATE_ALT_48 },
		{ "Compatibility / DESIGN", "ICON_DESIGN_UPLOAD_48", "ICON_DESIGN_UPLOAD_48", &ICON_DESIGN_UPLOAD_48 },
		{ "Compatibility / EDITOR", "ICON_EDITOR_BORDER_LEFT_48", "ICON_EDITOR_BORDER_LEFT_48", &ICON_EDITOR_BORDER_LEFT_48 },
		{ "Compatibility / EDITOR", "ICON_EDITOR_BORDER_RIGHT_48", "ICON_EDITOR_BORDER_RIGHT_48", &ICON_EDITOR_BORDER_RIGHT_48 },
		{ "Compatibility / EDITOR", "ICON_EDITOR_FORMAT_ALIGN_CENTER_48", "ICON_EDITOR_FORMAT_ALIGN_CENTER_48", &ICON_EDITOR_FORMAT_ALIGN_CENTER_48 },
		{ "Compatibility / EDITOR", "ICON_EDITOR_FORMAT_ALIGN_JUSTIFY_48", "ICON_EDITOR_FORMAT_ALIGN_JUSTIFY_48", &ICON_EDITOR_FORMAT_ALIGN_JUSTIFY_48 },
		{ "Compatibility / EDITOR", "ICON_EDITOR_FORMAT_ALIGN_LEFT_48", "ICON_EDITOR_FORMAT_ALIGN_LEFT_48", &ICON_EDITOR_FORMAT_ALIGN_LEFT_48 },
		{ "Compatibility / EDITOR", "ICON_EDITOR_FORMAT_ALIGN_RIGHT_48", "ICON_EDITOR_FORMAT_ALIGN_RIGHT_48", &ICON_EDITOR_FORMAT_ALIGN_RIGHT_48 },
		{ "Compatibility / EDITOR", "ICON_EDITOR_FORMAT_H3_48", "ICON_EDITOR_FORMAT_H3_48", &ICON_EDITOR_FORMAT_H3_48 },
		{ "Compatibility / EDITOR", "ICON_EDITOR_FORMAT_LETTER_SPACING_STANDARD_48", "ICON_EDITOR_FORMAT_LETTER_SPACING_STANDARD_48", &ICON_EDITOR_FORMAT_LETTER_SPACING_STANDARD_48 },
		{ "Compatibility / EDITOR", "ICON_EDITOR_FORMAT_SIZE_48", "ICON_EDITOR_FORMAT_SIZE_48", &ICON_EDITOR_FORMAT_SIZE_48 },
		{ "Compatibility / EDITOR", "ICON_EDITOR_MARGIN_48", "ICON_EDITOR_MARGIN_48", &ICON_EDITOR_MARGIN_48 },
		{ "Compatibility / EDITOR", "ICON_EDITOR_TITLECASE_48", "ICON_EDITOR_TITLECASE_48", &ICON_EDITOR_TITLECASE_48 },
		{ "Compatibility / COMMUNICATION", "ICON_COMMUNICATION_COMMENT_48", "ICON_COMMUNICATION_COMMENT_48", &ICON_COMMUNICATION_COMMENT_48 },
		{ "Compatibility / TOGGLE", "ICON_TOGGLE_CHECK_BOX_OUTLINE_BLANK_48", "ICON_TOGGLE_CHECK_BOX_OUTLINE_BLANK_48", &ICON_TOGGLE_CHECK_BOX_OUTLINE_BLANK_48 },
		{ "Compatibility / TOGGLE", "ICON_TOGGLE_RADIO_BUTTON_UNCHECKED_48", "ICON_TOGGLE_RADIO_BUTTON_UNCHECKED_48", &ICON_TOGGLE_RADIO_BUTTON_UNCHECKED_48 },
		{ "VIEW", "ICON_ACTION_FIT_SCREEN_OUTLINED", "ICON_ACTION_FIT_SCREEN_OUTLINED", &ICON_ACTION_FIT_SCREEN_OUTLINED },
		{ "IMAGE", "ICON_IMAGE_RESET_SHADOW_OUTLINED", "ICON_IMAGE_RESET_SHADOW_OUTLINED", &ICON_IMAGE_RESET_SHADOW_OUTLINED },
		{ "BRAND", "ICON_IMAGES_UPP_HEADING_ICON_OUTLINED", "ICON_IMAGES_UPP_HEADING_ICON_OUTLINED", &ICON_IMAGES_UPP_HEADING_ICON_OUTLINED },
		{ "VIEW", "ICON_IMAGE_VIEW_REAL_SIZE_OUTLINED", "ICON_IMAGE_VIEW_REAL_SIZE_OUTLINED", &ICON_IMAGE_VIEW_REAL_SIZE_OUTLINED },
		{ "BUSINESS", "ICON_BUSINES_GRAPH_1_OUTLINED", "ICON_BUSINES_GRAPH_1_OUTLINED", &ICON_BUSINES_GRAPH_1_OUTLINED },
		{ "VIEW", "ICON_UI_ACTION_RECENTER_OUTLINED", "ICON_UI_ACTION_RECENTER_OUTLINED", &ICON_UI_ACTION_RECENTER_OUTLINED },
		{ "Compatibility / DESIGN", "ICON_DESIGN_TRIP_ORIGIN_48", "ICON_DESIGN_TRIP_ORIGIN_48", &ICON_DESIGN_TRIP_ORIGIN_48 },
		{ "Compatibility / EDITOR", "ICON_EDITOR_MODE_OFF_ON_48", "ICON_EDITOR_MODE_OFF_ON_48", &ICON_EDITOR_MODE_OFF_ON_48 },
		{ "ACTION", "ICON_ACTION_REORDER_OUTLINED", "ICON_ACTION_REORDER_OUTLINED", &ICON_ACTION_REORDER_OUTLINED },
		{ "UiIcons", "ICON_ACTION_ARROW_CIRCLE_DOWN_OUTLINED", "ICON_ACTION_ARROW_CIRCLE_DOWN_OUTLINED", &ICON_ACTION_ARROW_CIRCLE_DOWN_OUTLINED },
		{ "UiIcons", "ICON_ACTION_ARROW_CIRCLE_RIGHT_OUTLINED", "ICON_ACTION_ARROW_CIRCLE_RIGHT_OUTLINED", &ICON_ACTION_ARROW_CIRCLE_RIGHT_OUTLINED },
		{ "UiIcons", "ICON_ACTION_ARROW_CIRCLE_UP_OUTLINED", "ICON_ACTION_ARROW_CIRCLE_UP_OUTLINED", &ICON_ACTION_ARROW_CIRCLE_UP_OUTLINED },
		{ "UiIcons", "ICON_UI_ACTION_SWAP_VERTICAL_CIRCLE_OUTLINED", "ICON_UI_ACTION_SWAP_VERTICAL_CIRCLE_OUTLINED", &ICON_UI_ACTION_SWAP_VERTICAL_CIRCLE_OUTLINED },
		{ "Compatibility / BRAND", "ICON_BRAND_NEWLOGO_V5_48", "ICON_BRAND_NEWLOGO_V5_48", &ICON_BRAND_NEWLOGO_V5_48 },
		{ "UiIcons", "ICON_EDITOR_BORDER_VERTICAL_OUTLINED", "ICON_EDITOR_BORDER_VERTICAL_OUTLINED", &ICON_EDITOR_BORDER_VERTICAL_OUTLINED },
	};
	count = (int)(sizeof(catalog) / sizeof(catalog[0]));
	return catalog;
}

inline const char* const* GetUIICONSCategories(int& count)
{
	static const char* categories[] = {
		"NAVIGATION",
		"HARDWARE",
		"CONTENT",
		"ACTION",
		"DESIGN",
		"EDITOR",
		"TOGGLE",
		"MEDIA",
		"SAMPLE",
		"Compatibility / NAVIGATION",
		"Compatibility / HARDWARE",
		"Compatibility / CONTENT",
		"Compatibility / ACTION",
		"Compatibility / DESIGN",
		"Compatibility / EDITOR",
		"Compatibility / COMMUNICATION",
		"Compatibility / TOGGLE",
		"VIEW",
		"IMAGE",
		"BRAND",
		"BUSINESS",
		"UiIcons",
		"Compatibility / BRAND",
	};
	count = (int)(sizeof(categories) / sizeof(categories[0]));
	return categories;
}


using UiIconFactoryFn = Image (*)();

inline String UiIconDisplayName(const String& raw_name)
{
    String s = raw_name;
    if(s.StartsWith("ICON_"))
        s = s.Mid(5);
    if(s.EndsWith("_48"))
        s = s.Left(s.GetCount() - 3);
    s.Replace("_", " ");
    s = ToLower(s);

    String out;
    bool word_start = true;
    for(int i = 0; i < s.GetCount(); i++) {
        int c = s[i];
        if(IsSpace(c)) {
            out.Cat(' ');
            word_start = true;
        }
        else {
            out.Cat(word_start ? ToUpper(c) : c);
            word_start = false;
        }
    }
    return out;
}

struct UiIconCatalogEntry : Moveable<UiIconCatalogEntry> {
    String          name;
    String          display_name;
    UiIconFactoryFn factory = nullptr;

    UiIconCatalogEntry() {}
    UiIconCatalogEntry(const String& n, UiIconFactoryFn f) : name(n), display_name(UiIconDisplayName(n)), factory(f) {}
    UiIconCatalogEntry(const String& n, const String& d, UiIconFactoryFn f) : name(n), display_name(d), factory(f) {}
};

inline const Vector<UiIconCatalogEntry>& UiIconCatalog()
{
    static const Vector<UiIconCatalogEntry> catalog = [] {
        Vector<UiIconCatalogEntry> out;
        int count = 0;
        const auto* rows = GetUIICONSCatalog(count);
        out.Reserve(count);
        for(int i = 0; i < count; ++i)
            out.Add(UiIconCatalogEntry(rows[i].symbol_name, rows[i].factory));
        return out;
    }();
    return catalog;
}

inline Vector<String> UiIconNameList()
{
    Vector<String> names;
    const Vector<UiIconCatalogEntry>& catalog = UiIconCatalog();
    names.Reserve(catalog.GetCount());
    for(int i = 0; i < catalog.GetCount(); i++)
        names.Add(catalog[i].name);
    return names;
}

inline Vector<String> UiIconDisplayNameList()
{
    Vector<String> names;
    const Vector<UiIconCatalogEntry>& catalog = UiIconCatalog();
    names.Reserve(catalog.GetCount());
    for(int i = 0; i < catalog.GetCount(); i++)
        names.Add(catalog[i].display_name);
    return names;
}

inline UiListModel UiIconListModel(bool use_icon_name_as_data = true)
{
    UiListModel model;
    const Vector<UiIconCatalogEntry>& catalog = UiIconCatalog();
    model.Reserve(catalog.GetCount());
    for(int i = 0; i < catalog.GetCount(); i++) {
        UiModelItem it;
        it.text = catalog[i].display_name;
        if(use_icon_name_as_data)
            it.data = catalog[i].name;
        it.icon = catalog[i].factory ? catalog[i].factory() : Image();
        it.icon_render_mode = UiIconRenderMode::MonoTint;
        model.Add(it);
    }
    return model;
}

inline Image UiIconFromName(const String& icon_name)
{
    const Vector<UiIconCatalogEntry>& catalog = UiIconCatalog();
    for(int i = 0; i < catalog.GetCount(); i++)
        if(icon_name == catalog[i].name)
            return catalog[i].factory ? catalog[i].factory() : Image();
    return Image();
}

}

#endif
